spring:
  application:
    name: beanflow
  datasource:
    url: ${BEANFLOW_DB_URL}
    username: ${BEANFLOW_DB_USERNAME}
    password: ${BEANFLOW_DB_PASSWORD}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
