package io.github.kdh949.beanflow.operations.api

import java.util.UUID

enum class OperatorPermission {
    EXPIRED_BENEFIT_POLICY_READ,
    EXPIRED_BENEFIT_POLICY_WRITE,
    POINT_ACCOUNT_READ,
    POINT_ADJUSTMENT,
    POINT_ACCRUAL_POLICY_READ,
    POINT_ACCRUAL_POLICY_WRITE,
    ORDER_COMPENSATION_READ,
    PAYMENT_CANCELLATION_SETUP_REPAIR,
    CUSTOMER_CANCELLATION_REFUND_RECONCILE,
    SUPPORT_CASE_READ,
    SUPPORT_CASE_WRITE,
    SUPPORT_CASE_ASSIGN,
    SUPPORT_SUBJECT_SEARCH,
    SUPPORT_VERIFICATION_MANAGE,
    SUPPORT_PII_REVEAL_REQUEST,
    SUPPORT_PII_REVEAL_APPROVE,
    SUPPORT_PII_REVEAL_BASIC,
    SUPPORT_PII_REVEAL_SENSITIVE,
    SUPPORT_BREAK_GLASS_REQUEST,
    SUPPORT_ACTION_REQUEST,
    SUPPORT_ACTION_APPROVE,
    SUPPORT_ACTION_EXECUTE,
    SUPPORT_ORDER_READ,
    SUPPORT_ORDER_CANCEL,
    SUPPORT_PICKUP_RESCHEDULE,
    SUPPORT_RESOLUTION_REQUEST,
    SUPPORT_RESOLUTION_APPROVE,
    SUPPORT_RESOLUTION_EXECUTE,
    SUPPORT_COMPENSATION_REQUEST,
    SUPPORT_COMPENSATION_APPROVE,
    SUPPORT_COMPENSATION_EXECUTE,
    SUPPORT_PROFILE_R1_CHANGE,
    SUPPORT_PROFILE_R2_CHANGE,
    SUPPORT_PROFILE_R3_REQUEST,
    SUPPORT_PROFILE_R3_APPROVE,
    SUPPORT_DELIVERY_READ,
    SUPPORT_DELIVERY_INCIDENT_WRITE,
    SUPPORT_DELIVERY_CHANGE,
    OPERATIONS_SUPPORT_INVESTIGATION,
    OPERATIONS_LEGAL_HOLD_MANAGE,
    OPERATIONS_RETENTION_MANAGE,
    PRIVACY_AUDIT_READ,
}

interface OperatorPermissionAuthorization {
    /**
     * Locks and validates the persistent grant in the caller's local transaction.
     */
    fun requireActive(
        actorId: UUID,
        permission: OperatorPermission,
    )
}
