import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent } from "storybook/test";
import { http, HttpResponse } from "msw";
import type { components } from "../../api/schema";
import { ManualRecoveryWorkspace } from "./ManualRecoveryWorkspace";
const targetId = "99000000-0000-4000-8000-000000000001";
const initialCase: components["schemas"]["ManualRecoveryCaseView"] = { caseId: "99000000-0000-4000-8000-000000000002", targetId, kind: "NOTIFICATION_DELIVERY", status: "MANUAL_REVIEW", version: 3, reason: "RETRY_EXHAUSTED", updatedAt: "2026-09-10T00:00:00Z", resolution: null };
let recoveryCase = initialCase;
let notification: components["schemas"]["NotificationRecoveryView"];
let publication: components["schemas"]["PublicationRecoveryView"];
let savedKey: string | null = null;
const handlers = [
  http.get("/api/v1/operations/notification-delivery-recoveries", () => HttpResponse.json({ items: [recoveryCase], nextCursor: null })),
  http.get("/api/v1/operations/event-publication-recoveries", () => HttpResponse.json({ items: [{ ...recoveryCase, kind: "EVENT_PUBLICATION" }], nextCursor: null })),
  http.get("/api/v1/operations/notification-delivery-recoveries/:id", () => HttpResponse.json({ ...notification, recoveryCase })),
  http.get("/api/v1/operations/event-publication-recoveries/:id", () => HttpResponse.json({ ...publication, recoveryCase })),
  http.post("/api/v1/operations/notification-delivery-recoveries/:id/retries", async ({ request }) => { expect(await request.json()).toEqual({ expectedVersion: 5, expectedCaseVersion: 3, reason: "연결 복구 확인" }); expect(request.headers.get("Idempotency-Key")).toBeTruthy(); recoveryCase = { ...recoveryCase, status: "RUNNING", version: 4 }; notification = { ...notification, state: "RETRY_SCHEDULED", version: 6 }; return HttpResponse.json({ commandId: targetId, acceptedAt: initialCase.updatedAt, recoveryCase }, { status: 202 }); }),
  http.post("/api/v1/operations/event-publication-recoveries/:id/retries", async ({ request }) => { expect(await request.json()).toEqual({ expectedCaseVersion: 3, reason: "연결 복구 확인" }); recoveryCase = { ...recoveryCase, status: "RUNNING", version: 4 }; publication = { ...publication, recoverable: false }; return HttpResponse.json({ commandId: targetId, acceptedAt: initialCase.updatedAt, recoveryCase }, { status: 202 }); }),
];
const meta = { title: "Patterns/Operations/Manual recovery", component: ManualRecoveryWorkspace, tags: ["autodocs"], args: { kind: "notification" }, beforeEach: () => { recoveryCase = { ...initialCase }; savedKey = null; notification = { deliveryId: targetId, state: "MANUAL_REVIEW", version: 5, attemptCount: 4, attemptLimit: 4, nextAttemptAt: null, lastFailureCode: "NOTIFICATION_SEND_FAILED", recoveryCase }; publication = { publicationId: targetId, eventType: "OrderReadyV1", listenerId: "OrderReadyCustomerNotificationListener", status: "FAILED", attemptCount: 4, completedAt: null, recoverable: true, recoveryCase, executionOutcome: "FAILED", retryBlockedReason: null }; }, parameters: { a11y: { test: "error" }, msw: { handlers }, docs: { description: { component: "알림/이벤트 전달의 원본 상태와 복구 Case를 분리해 확인합니다. 202는 추가 시도 접수이며 결과 불명/진행 중/해결 상태를 완료로 합치지 않습니다." }, story: { inline: false, height: "1050px" } } } } satisfies Meta<typeof ManualRecoveryWorkspace>;
export default meta; type Story = StoryObj<typeof meta>;
async function open(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"]) { await userEvent.click(await canvas.findByRole("button", { name: "복구 상세" })); }
async function retry(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"]) { await open(canvas); await userEvent.type(await canvas.findByLabelText("재시도 사유"), "연결 복구 확인"); await userEvent.click(canvas.getByRole("button", { name: "한 번 재시도 요청" })); }
export const NotificationRetry: Story = { play: async ({ canvas }) => { await retry(canvas); await expect(await canvas.findByText("재시도를 접수했습니다. 처리 결과를 다시 확인해 주세요.")).toBeVisible(); await expect(await canvas.findByText("복구 진행 중입니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "한 번 재시도 요청" })).not.toBeInTheDocument(); recoveryCase = { ...recoveryCase, status: "RESOLVED", resolution: "SUCCEEDED" }; notification = { ...notification, state: "SUCCEEDED" }; await userEvent.click(canvas.getByRole("button", { name: "복구 결과 다시 확인" })); await expect(await canvas.findByText("복구가 해결되었습니다")).toBeVisible(); } };
export const PublicationRetry: Story = { args: { kind: "publication" }, play: async ({ canvas }) => { await retry(canvas); await expect(await canvas.findByText("재시도를 접수했습니다. 처리 결과를 다시 확인해 주세요.")).toBeVisible(); } };
export const UnknownBlocked: Story = { args: { kind: "publication" }, beforeEach: () => { publication = { ...publication, executionOutcome: "UNKNOWN", recoverable: false, retryBlockedReason: "UNKNOWN_EXECUTION_REQUIRES_OWNER_RECONCILIATION" }; }, play: async ({ canvas }) => { await open(canvas); await expect(await canvas.findByText("실행 결과를 아직 확인하지 못했습니다")).toBeVisible(); await expect(canvas.getByText("업무 결과 조사 후 재실행 여부를 확인해야 합니다.")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "한 번 재시도 요청" })).not.toBeInTheDocument(); } };
export const UnknownAllowed: Story = { args: { kind: "publication" }, beforeEach: () => { publication = { ...publication, executionOutcome: "UNKNOWN" }; }, play: async ({ canvas }) => { await open(canvas); await expect(await canvas.findByText("실행 결과를 아직 확인하지 못했습니다")).toBeVisible(); await expect(canvas.getByRole("button", { name: "한 번 재시도 요청" })).toBeVisible(); } };
export const LostResponse: Story = { parameters: { msw: { handlers: [http.post("/api/v1/operations/notification-delivery-recoveries/:id/retries", ({ request }) => { if (!savedKey) { savedKey = request.headers.get("Idempotency-Key"); return HttpResponse.error(); } expect(request.headers.get("Idempotency-Key")).toBe(savedKey); recoveryCase = { ...recoveryCase, status: "RUNNING" }; return HttpResponse.json({ commandId: targetId, acceptedAt: initialCase.updatedAt, recoveryCase }, { status: 202 }); }), ...handlers] } }, play: async ({ canvas }) => { await retry(canvas); await expect(await canvas.findByRole("alert")).toBeVisible(); await userEvent.click(await canvas.findByRole("button", { name: "한 번 재시도 요청" })); await expect(await canvas.findByText("복구 진행 중입니다")).toBeVisible(); } };
export const StaleVersion: Story = { parameters: { msw: { handlers: [http.post("/api/v1/operations/notification-delivery-recoveries/:id/retries", () => { recoveryCase = { ...recoveryCase, status: "RUNNING" }; return HttpResponse.json({ code: "RESOURCE_STATE_CONFLICT", correlationId: "RECOVERY-CONFLICT" }, { status: 409 }); }), ...handlers] } }, play: async ({ canvas }) => { await retry(canvas); await expect(await canvas.findByText("문의 코드 RECOVERY-CONFLICT")).toBeVisible(); await expect(await canvas.findByText("복구 진행 중입니다")).toBeVisible(); } };
export const Pagination: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/notification-delivery-recoveries", ({ request }) => HttpResponse.json(new URL(request.url).searchParams.has("cursor") ? { items: [{ ...initialCase, reason: "OLDER_FAILURE" }], nextCursor: null } : { items: [initialCase], nextCursor: "next" })), ...handlers] } }, play: async ({ canvas }) => { await userEvent.click(await canvas.findByRole("button", { name: "다음 복구 내역" })); await expect(await canvas.findByText("OLDER_FAILURE")).toBeVisible(); await userEvent.click(canvas.getByRole("button", { name: "이전 복구 내역" })); await expect(await canvas.findByText("RETRY_EXHAUSTED")).toBeVisible(); } };
export const Empty: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/notification-delivery-recoveries", () => HttpResponse.json({ items: [], nextCursor: null }))] } }, play: async ({ canvas }) => { await expect(await canvas.findByText("복구 내역이 없습니다")).toBeVisible(); } };
export const Forbidden: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/notification-delivery-recoveries", () => HttpResponse.json({ code: "ACCESS_DENIED" }, { status: 403 }))] } }, play: async ({ canvas }) => { await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByText("복구 내역이 없습니다")).not.toBeInTheDocument(); } };

export const ResultUnavailable: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/notification-delivery-recoveries/:id", () => recoveryCase.status === "RUNNING" ? HttpResponse.json({ code: "DEPENDENCY_UNAVAILABLE" }, { status: 503 }) : HttpResponse.json({ ...notification, recoveryCase })), ...handlers] } }, play: async ({ canvas }) => { await retry(canvas); await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.getByText("재시도를 접수했습니다. 처리 결과를 다시 확인해 주세요.")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "한 번 재시도 요청" })).not.toBeInTheDocument(); await expect(canvas.queryByText("복구가 해결되었습니다")).not.toBeInTheDocument(); } };
export const PublicationCompleted: Story = { args: { kind: "publication" }, beforeEach: () => { recoveryCase = { ...recoveryCase, status: "RESOLVED", resolution: "SUCCEEDED" }; publication = { ...publication, status: "COMPLETED", completedAt: initialCase.updatedAt, executionOutcome: "SUCCEEDED", recoverable: false }; }, play: async ({ canvas }) => { await open(canvas); await expect(await canvas.findByText("전달 완료")).toBeVisible(); await expect(canvas.queryByText("픽업 완료")).not.toBeInTheDocument(); await expect(canvas.queryByRole("button", { name: "한 번 재시도 요청" })).not.toBeInTheDocument(); } };
