import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor } from "storybook/test";
import { http, HttpResponse } from "msw";
import MockDate from "mockdate";
import type { components } from "../../api/schema";
import { profileDigest } from "../../lib/supportProfilePayload";
import { OperationsSupportInvestigationPage } from "./OperationsSupportInvestigationPage";
const id = "84000000-0000-4000-8000-000000000001", investigationId = "84000000-0000-4000-8000-000000000002";
let compensation: components["schemas"]["SupportCompensationWorkflowResource"];
let request: components["schemas"]["SupportActionRequestResource"], profile: components["schemas"]["SupportProfileWorkflowResource"], workflow: components["schemas"]["OperationsSupportInvestigationWorkflowResource"];
const meta = { title: "Pages/Operations/Support investigation", component: OperationsSupportInvestigationPage, tags: ["autodocs"], async beforeEach() { MockDate.set("2026-09-11T09:04:00Z"); const digest = await profileDigest(id, 12, "CUSTOMER_PRIMARY_PHONE", { primaryPhone: "010-1234-5678" }); request = { requestId: id, caseId: id, action: "PROFILE_CHANGE", targetId: id, requesterActorId: id, executorActorId: id, revisionNumber: 1, state: "AWAITING_OPERATIONS", approvalRoute: "SUPPORT_MANAGER_THEN_OPERATIONS", actionPayloadDigest: digest, verificationSessionId: id, policyVersion: "profile-policy/v1", targetVersion: 12, amountKrw: null, evidenceDigest: "a".repeat(64), expiresAt: "2026-09-11T09:15:00Z", requestVersion: 2, approvalSteps: [], terminalExecutionId: null, terminalResolutionId: null, terminalCompensationId: null, terminalProfileChangeId: null }; profile = { profileChange: { profileChangeId: id, caseId: id, subjectType: "CUSTOMER", subjectId: id, purpose: "CUSTOMER_PRIMARY_PHONE", riskClass: "R3", requesterActorId: id, executorActorId: id, verificationSessionId: id, expectedProfileVersion: 12, currentProfileVersion: null, payloadDigest: digest, actionRequestId: id, state: "AWAITING_APPROVAL", notificationState: "NOT_REQUESTED", notificationFailureCode: null, maskedBefore: null, maskedAfter: null, version: 0, createdAt: "2026-09-11T09:00:00Z", updatedAt: "2026-09-11T09:00:00Z", notifications: [] }, approval: request, caseVersion: 5, currentProfileVersion: 12, verificationExpiresAt: request.expiresAt, allowedActions: [] }; workflow = { investigation: { investigationId, supportActionRequestId: id, supportActionRevisionId: id, revisionNumber: 1, state: "OPEN", openedAt: "2026-09-11T09:00:00Z", expiresAt: request.expiresAt, decidedByActorId: null, decidedAt: null, version: 3 }, canDecide: true }; return () => MockDate.reset(); }, parameters: { a11y: { test: "error" }, routing: { path: "/ops/support-investigations", initialEntry: `/ops/support-investigations?requestId=${id}` }, docs: { description: { component: "현재 승인안에 묶인 운영 조사를 찾아 별도 운영자의 결정을 기록합니다. 정정 원문은 다시 입력해 해시를 확인하며 승인과 실제 정보 변경·혜택 지급을 구분합니다." }, story: { inline: false, height: "1000px" } }, msw: { handlers: [http.get("/api/v1/support/action-requests/:id", () => HttpResponse.json(request)), http.get("/api/v1/operations/investigations", ({ request: httpRequest }) => { expect(new URL(httpRequest.url).searchParams.get("revisionNumber")).toBe("1"); return HttpResponse.json(workflow); }), http.get("/api/v1/support/profile-changes/:id/workflow", () => HttpResponse.json(profile)), http.get("/api/v1/support/compensations/:id/workflow", () => HttpResponse.json(compensation))] } } } satisfies Meta<typeof OperationsSupportInvestigationPage>;
export default meta; type Story = StoryObj<typeof meta>;
export const ApproveProfile: Story = { play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/operations/investigations/:id/decisions", async ({ request: httpRequest }) => { expect(await httpRequest.json()).toMatchObject({ expectedVersion: 3, decision: "APPROVE", reason: "승인안과 확인 내용 일치" }); request = { ...request, state: "READY_FOR_EXECUTION" }; workflow = { ...workflow, canDecide: false, investigation: { ...workflow.investigation, state: "APPROVED", version: 4 } }; return HttpResponse.json({ investigationId, requestId: id, revisionId: id, revisionNumber: 1, state: "APPROVED", supportRequestState: "READY_FOR_EXECUTION", supportRequestVersion: 3, decidedByActorId: investigationId, decidedAt: "2026-09-11T09:04:00Z", version: 4 }); })); await userEvent.type(await canvas.findByLabelText("새 기본 전화번호"), "010-1234-5678"); await userEvent.type(canvas.getByLabelText("운영 검토 사유"), "승인안과 확인 내용 일치"); await userEvent.type(canvas.getByLabelText("운영 검토 증빙 참조"), "조사 기록 7"); await waitFor(() => expect(canvas.getByRole("button", { name: "운영 검토 결정 기록" })).toBeEnabled()); await userEvent.click(canvas.getByRole("button", { name: "운영 검토 결정 기록" })); await expect(await canvas.findByText("운영 결정을 기록했습니다")).toBeVisible(); await expect(canvas.getAllByText("실행 준비").length).toBeGreaterThan(0); await expect(canvas.queryByDisplayValue("010-1234-5678")).not.toBeInTheDocument(); } };
export const SeparateActorRequired: Story = { beforeEach() { workflow.canDecide = false; }, play: async ({ canvas }) => { await expect(await canvas.findByText("현재 계정에서 결정할 수 없습니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "운영 검토 결정 기록" })).not.toBeInTheDocument(); } };
export const StaleBinding: Story = { beforeEach() { profile.approval = { ...request, revisionNumber: 2 }; }, play: async ({ canvas }) => { await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "운영 검토 결정 기록" })).not.toBeInTheDocument(); } };
export const ReturnForRevision: Story = { play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/operations/investigations/:id/decisions", async ({ request: httpRequest }) => { expect(await httpRequest.json()).toMatchObject({ expectedVersion: 3, decision: "RETURN_FOR_REVISION" }); return HttpResponse.json({ investigationId, requestId: id, revisionId: id, revisionNumber: 1, state: "RETURNED", supportRequestState: "REVISION_REQUIRED", supportRequestVersion: 3, decidedByActorId: investigationId, decidedAt: "2026-09-11T09:04:00Z", version: 4 }); })); await userEvent.selectOptions(await canvas.findByLabelText("운영 검토 결정"), "RETURN_FOR_REVISION"); await userEvent.type(canvas.getByLabelText("운영 검토 사유"), "증빙 보완 필요"); await userEvent.type(canvas.getByLabelText("운영 검토 증빙 참조"), "조사 기록 8"); await userEvent.click(canvas.getByRole("button", { name: "운영 검토 결정 기록" })); await expect(await canvas.findByText("수정 필요")).toBeVisible(); } };
export const UnknownDecision: Story = { play: async ({ canvas, msw }) => { let key = "", calls = 0; msw.use(http.post("/api/v1/operations/investigations/:id/decisions", ({ request: httpRequest }) => { calls++; if (calls === 1) { key = httpRequest.headers.get("Idempotency-Key")!; return HttpResponse.error(); } expect(httpRequest.headers.get("Idempotency-Key")).toBe(key); return HttpResponse.json({ investigationId, requestId: id, revisionId: id, revisionNumber: 1, state: "ESCALATED", supportRequestState: "MANUAL_REVIEW", supportRequestVersion: 3, decidedByActorId: investigationId, decidedAt: "2026-09-11T09:04:00Z", version: 4 }); })); await userEvent.selectOptions(await canvas.findByLabelText("운영 검토 결정"), "ESCALATE"); await userEvent.type(canvas.getByLabelText("운영 검토 사유"), "추가 조사 필요"); await userEvent.type(canvas.getByLabelText("운영 검토 증빙 참조"), "조사 기록 9"); await userEvent.click(canvas.getByRole("button", { name: "운영 검토 결정 기록" })); await userEvent.click(await canvas.findByRole("button", { name: "같은 운영 결정 확인" })); await expect(await canvas.findByText("수동 확인 필요")).toBeVisible(); expect(calls).toBe(2); } };

export const CouponCostReview: Story = { beforeEach() { request = { ...request, action: "GOODWILL_COMPENSATION", actionPayloadDigest: "c".repeat(64) }; compensation = { request: { compensationRequestId: id, supportCaseId: id, incidentId: id, orderId: id, storeId: id, benefitType: "COUPON", amountKrw: 1000, couponTemplateId: id, policyVersionId: id, band: "MEDIUM", approvalRoute: "SUPPORT_MANAGER_THEN_OPERATIONS", actionRequestId: id, state: "AWAITING_APPROVAL", payloadDigest: request.actionPayloadDigest, terminalBenefitId: null, benefitIssuedAt: null, notificationDeliveryId: null, notificationState: null, notificationFailureCode: null, version: 0, createdAt: "2026-09-11T09:00:00Z", updatedAt: "2026-09-11T09:00:00Z" }, terms: { responsibility: "SHARED", evidenceBasis: "OPERATIONS_FINDING", costEvidenceDigest: "d".repeat(64), platformShareBps: 2500, storeShareBps: 7500, evidenceDigest: "a".repeat(64), targetVersion: 12 }, approval: { requestId: id, revisionNumber: 1, requestVersion: 2, state: "AWAITING_OPERATIONS", caseVersion: 5, executorActorId: id }, currentTargetVersion: 12, verificationExpiresAt: request.expiresAt, allowedActions: [], couponTemplate: { templateId: id, amountKrw: 1000, validityDays: 30, minimumEligibleSubtotalKrw: 3000 } }; }, play: async ({ canvas }) => { await expect(await canvas.findByText(/쿠폰 사용 기한 30일/)).toBeVisible(); await expect(canvas.getByText(/플랫폼 25% · 매장 75%/)).toBeVisible(); await userEvent.type(canvas.getByLabelText("운영 검토 사유"), "혜택과 비용 확인"); await userEvent.type(canvas.getByLabelText("운영 검토 증빙 참조"), "조사 기록 10"); await expect(canvas.getByRole("button", { name: "운영 검토 결정 기록" })).toBeDisabled(); await userEvent.click(canvas.getByRole("checkbox", { name: "보상 혜택과 비용 조건을 확인했습니다" })); await expect(canvas.getByRole("button", { name: "운영 검토 결정 기록" })).toBeEnabled(); } };

export const SelectInvestigation: Story = {
  parameters: { routing: { path: "/ops/support-investigations", initialEntry: "/ops/support-investigations" } },
  play: async ({ canvas, msw }) => {
    msw.use(http.get("/api/v1/operations/investigation-queue", () => HttpResponse.json({ items: [{ investigationId, request: { requestId: id, action: "PROFILE_CHANGE", caseCategory: "ACCOUNT_RECOVERY", caseOpenedAt: "2026-09-11T09:00:00Z", revisionNumber: 1 }, state: "OPEN", openedAt: "2026-09-11T09:01:00Z", expiresAt: request.expiresAt, canDecide: true }], nextCursor: null })));
    await userEvent.click(await canvas.findByRole("button", { name: "이 검토 열기" }));
    await expect(await canvas.findByLabelText("새 기본 전화번호")).toBeVisible();
    await expect(canvas.queryByLabelText("검토할 상담 요청 ID")).not.toBeInTheDocument();
  },
};
export const EmptyInvestigationQueue: Story = {
  parameters: { routing: { path: "/ops/support-investigations", initialEntry: "/ops/support-investigations" }, msw: { handlers: [http.get("/api/v1/operations/investigation-queue", () => HttpResponse.json({ items: [], nextCursor: null }))] } },
  play: async ({ canvas }) => { await expect(await canvas.findByText("현재 조회 구간에 검토 요청이 없습니다")).toBeVisible(); },
};
