import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent } from "storybook/test";
import { http, HttpResponse } from "msw";
import MockDate from "mockdate";
import type { components } from "../../api/schema";
import { profileDigest } from "../../lib/supportProfilePayload";
import { OperationsSupportInvestigationPage } from "./OperationsSupportInvestigationPage";
const id = "84000000-0000-4000-8000-000000000001", investigationId = "84000000-0000-4000-8000-000000000002";
let compensation: components["schemas"]["SupportCompensationWorkflowResource"];
let request: components["schemas"]["SupportActionRequestResource"], profile: components["schemas"]["SupportProfileWorkflowResource"], workflow: components["schemas"]["OperationsSupportInvestigationWorkflowResource"];
const meta = { title: "Pages/Operations/Support investigation", component: OperationsSupportInvestigationPage, tags: ["autodocs"], async beforeEach() { MockDate.set("2026-09-11T09:04:00Z"); const digest = await profileDigest(id, 12, "CUSTOMER_PRIMARY_PHONE", { primaryPhone: "010-1234-5678" }); request = { requestId: id, caseId: id, action: "PROFILE_CHANGE", targetId: id, requesterActorId: id, executorActorId: id, revisionNumber: 1, state: "AWAITING_OPERATIONS", approvalRoute: "SUPPORT_MANAGER_THEN_OPERATIONS", actionPayloadDigest: digest, verificationSessionId: id, policyVersion: "profile-policy/v1", targetVersion: 12, amountKrw: null, evidenceDigest: "a".repeat(64), expiresAt: "2026-09-11T09:15:00Z", requestVersion: 2, approvalSteps: [], terminalExecutionId: null, terminalResolutionId: null, terminalCompensationId: null, terminalProfileChangeId: null }; profile = { profileChange: { profileChangeId: id, caseId: id, subjectType: "CUSTOMER", subjectId: id, purpose: "CUSTOMER_PRIMARY_PHONE", riskClass: "R3", requesterActorId: id, executorActorId: id, verificationSessionId: id, expectedProfileVersion: 12, currentProfileVersion: null, payloadDigest: digest, actionRequestId: id, state: "AWAITING_APPROVAL", notificationState: "NOT_REQUESTED", notificationFailureCode: null, maskedBefore: null, maskedAfter: null, version: 0, createdAt: "2026-09-11T09:00:00Z", updatedAt: "2026-09-11T09:00:00Z", notifications: [] }, approval: request, caseVersion: 5, currentProfileVersion: 12, executionExpiresAt: request.expiresAt, allowedActions: [] }; workflow = { investigation: { investigationId, supportActionRequestId: id, supportActionRevisionId: id, revisionNumber: 1, state: "OPEN", openedAt: "2026-09-11T09:00:00Z", expiresAt: request.expiresAt, decidedByActorId: null, decidedAt: null, version: 3 }, canDecide: false }; return () => MockDate.reset(); }, parameters: { a11y: { test: "error" }, routing: { path: "/ops/support-investigations", initialEntry: `/ops/support-investigations?requestId=${id}` }, docs: { description: { component: "과거 운영 조사와 승인 이력을 조회합니다. 이전 미실행 요청은 같은 상담의 담당자가 새 요청으로 작성하며 새로운 승인 결정이나 원문 입력을 받지 않습니다." }, story: { inline: false, height: "1000px" } }, msw: { handlers: [http.get("/api/v1/operations/support-action-requests/:id/review", () => HttpResponse.json({
  request: { requestId: request.requestId, caseId: request.caseId, action: request.action, targetId: request.targetId, revisionNumber: request.revisionNumber, requestVersion: request.requestVersion, state: request.state, actionPayloadDigest: request.actionPayloadDigest, targetVersion: request.targetVersion, evidenceDigest: request.evidenceDigest },
  profile: request.action === "PROFILE_CHANGE" ? { subjectId: profile.profileChange.subjectId, purpose: profile.profileChange.purpose, expectedProfileVersion: profile.profileChange.expectedProfileVersion, currentProfileVersion: profile.currentProfileVersion, payloadDigest: profile.profileChange.payloadDigest } : null,
  compensation: request.action === "GOODWILL_COMPENSATION" ? { incidentId: compensation.request.incidentId, orderId: compensation.request.orderId, benefitType: compensation.request.benefitType, amountKrw: compensation.request.amountKrw, payloadDigest: compensation.request.payloadDigest, terms: compensation.terms, currentTargetVersion: compensation.currentTargetVersion, couponTemplate: compensation.couponTemplate } : null,
})), http.get("/api/v1/support/action-requests/:id", () => { throw new Error("Operations-only reviewer must not read Support case API"); }), http.get("/api/v1/operations/investigations", ({ request: httpRequest }) => { expect(new URL(httpRequest.url).searchParams.get("revisionNumber")).toBe("1"); return HttpResponse.json(workflow); }), http.get("/api/v1/support/profile-changes/:id/workflow", () => HttpResponse.json(profile)), http.get("/api/v1/support/compensations/:id/workflow", () => HttpResponse.json(compensation))] } } } satisfies Meta<typeof OperationsSupportInvestigationPage>;
export default meta; type Story = StoryObj<typeof meta>;
export const LegacyRequestRequiresRecreation: Story = { play: async ({ canvas }) => { await expect(await canvas.findByText("이전 정책의 요청입니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "운영 검토 결정 기록" })).not.toBeInTheDocument(); await expect(canvas.queryByLabelText("새 기본 전화번호")).not.toBeInTheDocument(); } };
export const HistoricalApproval: Story = { beforeEach() { workflow.investigation.state = "APPROVED"; request.state = "EXECUTED"; }, play: async ({ canvas }) => { await expect(await canvas.findByText("승인")).toBeVisible(); await expect(canvas.getByText("실행 완료")).toBeVisible(); await expect(canvas.getByText("과거 처리 이력입니다")).toBeVisible(); } };
export const HistoricalReturn: Story = { beforeEach() { workflow.investigation.state = "RETURNED"; request.state = "REVISION_REQUIRED"; }, play: async ({ canvas }) => { await expect(await canvas.findByText("수정 요청")).toBeVisible(); await expect(canvas.getByText("이전 정책의 요청입니다")).toBeVisible(); } };
export const ExpiredHistory: Story = { beforeEach() { workflow.investigation.state = "EXPIRED"; request.state = "EXPIRED"; }, play: async ({ canvas }) => { await expect(await canvas.findByText("이전 정책의 요청입니다")).toBeVisible(); await expect(canvas.getAllByText("만료").length).toBeGreaterThan(0); } };
export const ReadFailure: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/support-action-requests/:id/review", () => HttpResponse.json({ code: "DEPENDENCY_UNAVAILABLE", message: "Read failed", correlationId: "story-failure" }, { status: 503 }))] } }, play: async ({ canvas }) => { await expect(await canvas.findByRole("alert")).toBeVisible(); } };
export const PermissionDenied: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/support-action-requests/:id/review", () => HttpResponse.json({ code: "ACCESS_DENIED", message: "Denied", correlationId: "story-denied" }, { status: 403 }))] } }, play: async ({ canvas }) => { await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByText("현재 승인안 검토")).not.toBeInTheDocument(); } };

export const CouponCostReview: Story = { beforeEach() { request = { ...request, action: "GOODWILL_COMPENSATION", actionPayloadDigest: "c".repeat(64) }; compensation = { request: { compensationRequestId: id, supportCaseId: id, incidentId: id, orderId: id, storeId: id, benefitType: "COUPON", amountKrw: 1000, couponTemplateId: id, policyVersionId: id, band: "MEDIUM", approvalRoute: "SUPPORT_MANAGER_THEN_OPERATIONS", actionRequestId: id, state: "AWAITING_APPROVAL", payloadDigest: request.actionPayloadDigest, terminalBenefitId: null, benefitIssuedAt: null, notificationDeliveryId: null, notificationState: null, notificationFailureCode: null, version: 0, createdAt: "2026-09-11T09:00:00Z", updatedAt: "2026-09-11T09:00:00Z" }, terms: { responsibility: "SHARED", evidenceBasis: "OPERATIONS_FINDING", costEvidenceDigest: "d".repeat(64), platformShareBps: 2500, storeShareBps: 7500, evidenceDigest: "a".repeat(64), targetVersion: 12 }, approval: { requestId: id, revisionNumber: 1, requestVersion: 2, state: "AWAITING_OPERATIONS", caseVersion: 5, executorActorId: id }, currentTargetVersion: 12, executionExpiresAt: request.expiresAt, allowedActions: [], couponTemplate: { templateId: id, amountKrw: 1000, validityDays: 30, minimumEligibleSubtotalKrw: 3000 } }; }, play: async ({ canvas }) => { await expect(await canvas.findByText(/쿠폰 사용 기한 30일/)).toBeVisible(); await expect(canvas.getByText(/플랫폼 25% · 매장 75%/)).toBeVisible(); await expect(canvas.queryByRole("checkbox")).not.toBeInTheDocument(); await expect(canvas.queryByRole("button", { name: "운영 검토 결정 기록" })).not.toBeInTheDocument(); } };

export const SelectInvestigation: Story = {
  parameters: { routing: { path: "/ops/support-investigations", initialEntry: "/ops/support-investigations" } },
  play: async ({ canvas, msw }) => {
    msw.use(http.get("/api/v1/operations/investigation-queue", () => HttpResponse.json({ items: [{ investigationId, request: { requestId: id, action: "PROFILE_CHANGE", caseCategory: "ACCOUNT_RECOVERY", caseOpenedAt: "2026-09-11T09:00:00Z", revisionNumber: 1 }, state: "OPEN", openedAt: "2026-09-11T09:01:00Z", expiresAt: request.expiresAt, canDecide: false }], nextCursor: null })));
    await userEvent.click(await canvas.findByRole("button", { name: "이 검토 열기" }));
    await expect(await canvas.findByText("이전 정책의 요청입니다")).toBeVisible();
    await expect(canvas.queryByLabelText("검토할 상담 요청 ID")).not.toBeInTheDocument();
  },
};
export const EmptyInvestigationQueue: Story = {
  parameters: { routing: { path: "/ops/support-investigations", initialEntry: "/ops/support-investigations" }, msw: { handlers: [http.get("/api/v1/operations/investigation-queue", () => HttpResponse.json({ items: [], nextCursor: null }))] } },
  play: async ({ canvas }) => { await expect(await canvas.findByText("현재 조회 구간에 검토 요청이 없습니다")).toBeVisible(); },
};
