import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor } from "storybook/test";
import { http, HttpResponse } from "msw";
import { ids } from "../../../.storybook/fixtures";
import { OperationsControlPage } from "./OperationsControlPage";
const original = { disputeId: "92000000-0000-4000-8000-000000000001", storeId: ids.store, settlementItemId: "91000000-0000-4000-8000-000000000001", state: "FILED", version: 0, expectedAdjustmentKrw: 3500, heldAmountKrw: 3500, reason: "부분 환불 조정액 확인", evidenceReferences: ["support-evidence://original"], filedAt: "2026-09-10T00:00:00Z", decidedAt: null, settlementAdjustmentId: null, pendingDecision: null };
let record = original;
const handlers = [http.get("/api/v1/operations/settlement-disputes", ({ request }) => { expect(new URL(request.url).searchParams.get("storeId")).toBe(ids.store); return HttpResponse.json({ items: [record], page: {} }); }), http.get("/api/v1/operations/settlement-disputes/:id", () => HttpResponse.json(record)), http.post("/api/v1/operations/settlement-disputes/:id/reviews", async ({ request }) => { expect(await request.json()).toMatchObject({ expectedVersion: 0 }); expect(request.headers.get("Idempotency-Key")).toBeTruthy(); record = { ...record, state: "UNDER_REVIEW", version: 1 }; return HttpResponse.json(record); }), http.post("/api/v1/operations/settlement-disputes/:id/decisions", async ({ request }) => { expect(await request.json()).toMatchObject({ outcome: "REJECTED", expectedVersion: 1, reason: "이미 정산에 반영됨" }); record = { ...record, state: "REJECTED", version: 2 }; return HttpResponse.json(record); })];
const meta = { title: "Pages/Operations/Control", component: OperationsControlPage, tags: ["autodocs"], beforeEach: () => { record = original; }, parameters: { a11y: { test: "error" }, msw: { handlers }, routing: { path: "/ops/control", initialEntry: "/ops/control" }, docs: { description: { component: "매장별 정산 이의 목록·상태 필터·상세와 운영자 검토·판정을 실제 API로 처리합니다." }, story: { inline: false, height: "1150px" } } } } satisfies Meta<typeof OperationsControlPage>;
export default meta; type Story = StoryObj<typeof meta>;
async function query(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"]) { await userEvent.type(canvas.getByLabelText("이의제기 매장 ID"), ids.store); await userEvent.click(canvas.getByRole("button", { name: "이의제기 조회" })); }
export const ReviewAndReject: Story = { play: async ({ canvas }) => { await query(canvas); await userEvent.click(await canvas.findByRole("button", { name: "이의제기 상세" })); await userEvent.type(await canvas.findByLabelText("처리 사유"), "환불 자료 검토"); await userEvent.click(canvas.getByRole("button", { name: "검토 시작" })); await canvas.findByRole("button", { name: "기각 판정" }); await waitFor(() => expect(canvas.getByLabelText("처리 사유")).toBeEnabled()); await userEvent.type(canvas.getByLabelText("처리 사유"), "이미 정산에 반영됨"); await userEvent.click(canvas.getByRole("button", { name: "기각 판정" })); await expect(await canvas.findByText("처리 요청을 완료했습니다.")).toBeVisible(); await expect(await canvas.findByText("기각")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "인정 판정" })).not.toBeInTheDocument(); } };
export const PaginationAndFilter: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/settlement-disputes", ({ request }) => { const query = new URL(request.url).searchParams; if (query.get("state") === "ACCEPTED") return HttpResponse.json({ items: [], page: {} }); return HttpResponse.json({ items: [{ ...original, expectedAdjustmentKrw: query.has("cursor") ? 500 : 3500 }], page: { nextCursor: query.has("cursor") ? undefined : "next" } }); }), ...handlers] } }, play: async ({ canvas }) => { await query(canvas); await userEvent.click(await canvas.findByRole("button", { name: "다음 이의제기" })); await expect(await canvas.findByText("₩500")).toBeVisible(); await userEvent.click(canvas.getByRole("button", { name: "이전 이의제기" })); await expect(await canvas.findByText("₩3,500")).toBeVisible(); await userEvent.selectOptions(canvas.getByLabelText("이의제기 상태"), "ACCEPTED"); await userEvent.click(canvas.getByRole("button", { name: "이의제기 조회" })); await expect(await canvas.findByText("조건에 맞는 이의제기가 없습니다")).toBeVisible(); } };
export const Unavailable: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/settlement-disputes", () => HttpResponse.json({ code: "DEPENDENCY_UNAVAILABLE" }, { status: 503 }))] } }, play: async ({ canvas }) => { await query(canvas); await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByText("조건에 맞는 이의제기가 없습니다")).not.toBeInTheDocument(); } };
