import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor } from "storybook/test";
import { http, HttpResponse } from "msw";
import MockDate from "mockdate";
import type { components } from "../../api/schema";
import { PaymentRepairWorkspace } from "./PaymentRepairWorkspace";
const caseId = "98000000-0000-4000-8000-000000000001";
const proposer = "98000000-0000-4000-8000-000000000002";
const approver = "98000000-0000-4000-8000-000000000003";
const original: components["schemas"]["RepairProposal"] = { proposalId: "98000000-0000-4000-8000-000000000004", caseId, action: "RECREATE_MISSING_CANCELLATION_REFUND", state: "PENDING_APPROVAL", proposedBy: proposer, createdAt: "2026-09-11T00:00:00Z", expiresAt: "2026-09-11T00:30:00Z", correlationId: "REPAIR-PROPOSED" };
let proposal = original;
let actor = approver;
let key: string | null = null;
const handlers = [http.get("/api/v1/operations/me", () => HttpResponse.json({ actorType: "OPERATOR", operatorId: actor, roles: ["PLATFORM_OPERATOR"] })), http.get("/api/v1/operations/reprocessing-repair-proposals/:id", () => HttpResponse.json(proposal)), http.post("/api/v1/operations/reprocessing-cases/:id/repair-proposals", async ({ request }) => { expect(await request.json()).toEqual({ reason: "누락 환불 기록 확인" }); expect(request.headers.get("Idempotency-Key")).toBeTruthy(); return HttpResponse.json(proposal, { status: 201 }); }), http.post("/api/v1/operations/reprocessing-repair-proposals/:id/decisions", async ({ request }) => { const body = await request.json(); expect(body).toEqual({ decision: "APPROVE", reason: "다른 담당자 검증 완료" }); proposal = { ...original, state: "EXECUTED", decidedBy: approver, decidedAt: "2026-09-11T00:01:00Z" }; return HttpResponse.json(proposal); })];
const meta = { title: "Patterns/Operations/Payment setup repair", component: PaymentRepairWorkspace, tags: ["autodocs"], args: { caseId }, beforeEach: () => { MockDate.set("2026-09-11T00:01:00Z"); proposal = original; actor = approver; key = null; return () => MockDate.reset(); }, parameters: { a11y: { test: "error" }, msw: { handlers }, docs: { description: { component: "복구 제안 생성과 다른 담당자의 현재 제안 조회·승인/반려를 연결합니다. 만료와 자기 판정을 막고 실행은 실제 환불 완료와 구분합니다." }, story: { inline: false, height: "1050px" } } } } satisfies Meta<typeof PaymentRepairWorkspace>;
export default meta; type Story = StoryObj<typeof meta>;
async function read(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"]) { await userEvent.type(canvas.getByLabelText("복구 제안 ID"), original.proposalId); await userEvent.click(canvas.getByRole("button", { name: "현재 복구 제안 조회" })); }
export const Propose: Story = { play: async ({ canvas }) => { await userEvent.type(canvas.getByLabelText("복구 제안 사유"), "누락 환불 기록 확인"); await userEvent.click(canvas.getByRole("button", { name: "복구 제안 생성" })); await expect(await canvas.findByText("복구 제안을 만들었습니다. 다른 담당자의 판정이 필요합니다.")).toBeVisible(); await expect(await canvas.findByText(original.proposalId)).toBeVisible(); } };
export const Approve: Story = { play: async ({ canvas }) => { await read(canvas); await userEvent.type(await canvas.findByLabelText("복구 판정 사유"), "다른 담당자 검증 완료"); await userEvent.click(canvas.getByRole("button", { name: "복구 승인" })); await expect(await canvas.findByText("환불 결과 조회를 위한 복구가 실행되었습니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "복구 승인" })).not.toBeInTheDocument(); } };
export const SelfDecisionBlocked: Story = { beforeEach: () => { actor = proposer; }, play: async ({ canvas }) => { await read(canvas); await expect(await canvas.findByText("제안자와 다른 담당자가 판정해야 합니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "복구 승인" })).not.toBeInTheDocument(); } };
export const Expired: Story = { beforeEach: () => { proposal = { ...original, state: "EXPIRED" }; }, play: async ({ canvas }) => { await read(canvas); await expect(await canvas.findByText("복구 제안의 승인 기한이 지났습니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "복구 승인" })).not.toBeInTheDocument(); } };
export const Stale: Story = { parameters: { msw: { handlers: [http.post("/api/v1/operations/reprocessing-repair-proposals/:id/decisions", () => { proposal = { ...proposal, state: "STALE" }; return HttpResponse.json({ code: "REPROCESSING_PROPOSAL_STALE", correlationId: "REPAIR-STALE" }, { status: 409 }); }), ...handlers] } }, play: async ({ canvas }) => { await read(canvas); await userEvent.type(await canvas.findByLabelText("복구 판정 사유"), "다른 담당자 검증 완료"); await userEvent.click(canvas.getByRole("button", { name: "복구 승인" })); await expect(await canvas.findByText("문의 코드 REPAIR-STALE")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "복구 승인" })).not.toBeInTheDocument(); } };
export const LostResponse: Story = { parameters: { msw: { handlers: [http.post("/api/v1/operations/reprocessing-repair-proposals/:id/decisions", ({ request }) => { if (!key) { key = request.headers.get("Idempotency-Key"); return HttpResponse.error(); } expect(request.headers.get("Idempotency-Key")).toBe(key); proposal = { ...proposal, state: "REJECTED" }; return HttpResponse.json(proposal); }), ...handlers] } }, play: async ({ canvas }) => { await read(canvas); await userEvent.type(await canvas.findByLabelText("복구 판정 사유"), "새 제안이 필요함"); await userEvent.click(canvas.getByRole("button", { name: "복구 반려" })); await expect(await canvas.findByRole("alert")).toBeVisible(); await userEvent.click(await canvas.findByRole("button", { name: "복구 반려" })); await expect(await canvas.findByText("반려됨")).toBeVisible(); } };
export const Forbidden: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/reprocessing-repair-proposals/:id", () => HttpResponse.json({ code: "ACCESS_DENIED" }, { status: 403 })), ...handlers] } }, play: async ({ canvas }) => { await read(canvas); await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "복구 승인" })).not.toBeInTheDocument(); } };

export const BrowserClockAhead: Story = { ...Approve, beforeEach: () => { MockDate.set("2026-09-12T00:00:00Z"); } };
export const NewProposalClearsPreviousDecision: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/reprocessing-repair-proposals/:id", ({ params }) => HttpResponse.json({ ...original, proposalId: params.id })), ...handlers] } }, play: async ({ canvas }) => {
  await userEvent.type(canvas.getByLabelText("복구 제안 사유"), "누락 환불 기록 확인");
  await userEvent.click(canvas.getByRole("button", { name: "복구 제안 생성" }));
  await expect(await canvas.findByText("복구 제안을 만들었습니다. 다른 담당자의 판정이 필요합니다.")).toBeVisible();
  await userEvent.type(await canvas.findByLabelText("복구 판정 사유"), "이전 제안에만 해당하는 사유");
  await userEvent.clear(canvas.getByLabelText("복구 제안 ID"));
  const nextId = "98000000-0000-4000-8000-000000000099";
  await userEvent.type(canvas.getByLabelText("복구 제안 ID"), nextId);
  await userEvent.click(canvas.getByRole("button", { name: "현재 복구 제안 조회" }));
  await expect(await canvas.findByText(nextId)).toBeVisible();
  await waitFor(() => expect(canvas.getByLabelText("복구 판정 사유")).toHaveValue(""));
  await expect(canvas.queryByText("복구 제안을 만들었습니다. 다른 담당자의 판정이 필요합니다.")).not.toBeInTheDocument();
  await expect(canvas.getByRole("button", { name: "복구 승인" })).toBeDisabled();
} };
