import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent } from "storybook/test";
import { http, HttpResponse } from "msw";
import { ids } from "../../../.storybook/fixtures";
import { PointPolicyHistory } from "./PointPolicyHistory";

const version = { policyVersionId: 12, scopeType: "STORE", scopeReference: ids.store, state: "OVERRIDE", accrualRateBps: 500, roundingMode: "FLOOR", issuerType: "PLATFORM", issuerReference: "platform:beanflow", expiryRule: "SEOUL_CALENDAR_DAYS_FROM_COMPLETION", validityDays: 365, effectiveAt: "2026-09-11T00:00:00Z", actorType: "PLATFORM_OPERATOR", actorReference: "operator-1", reason: "매장 적립 조건 적용" };
const inheritance = { policyVersionId: 11, scopeType: "STORE", scopeReference: ids.store, state: "INHERIT_GLOBAL", effectiveAt: "2025-09-11T00:00:00Z", actorType: "PLATFORM_OPERATOR", actorReference: "operator-1", reason: "공통 정책으로 복귀" };
const handler = http.get("/api/v1/operations/policies/ordinary-point-accrual/stores/:storeId/versions", ({ request }) => { expect(request.headers.get("X-Access-Reason")).toBe("POLICY_AUDIT_REVIEW"); return HttpResponse.json(new URL(request.url).searchParams.has("cursor") ? { items: [inheritance], page: { nextCursor: null } } : { items: [version], page: { nextCursor: "history-next" } }); });
const meta = { title: "Patterns/Operations/Point policy history", component: PointPolicyHistory, tags: ["autodocs"], args: { storeId: ids.store }, parameters: { a11y: { test: "error" }, msw: { handlers: [handler] }, docs: { description: { component: "공통 또는 매장 포인트 정책의 감사 이력을 조회합니다. 상속 버전에는 과거 적립률을 추정해 표시하지 않으며 연도와 변경 사유를 함께 제공합니다." }, story: { inline: false, height: "800px" } } } } satisfies Meta<typeof PointPolicyHistory>;
export default meta; type Story = StoryObj<typeof meta>;
export const StoreHistory: Story = { play: async ({ canvas }) => { await userEvent.selectOptions(canvas.getByLabelText("포인트 이력 조회 사유"), "POLICY_AUDIT_REVIEW"); await userEvent.click(canvas.getByRole("button", { name: "포인트 변경 이력 조회" })); await expect(await canvas.findByText("매장 적립 조건 적용")).toBeVisible(); await userEvent.click(canvas.getByRole("button", { name: "다음 포인트 이력" })); await expect(await canvas.findByText("공통 정책으로 복귀")).toBeVisible(); await expect(canvas.queryByText("5.00%")).not.toBeInTheDocument(); await userEvent.click(canvas.getByRole("button", { name: "이전 포인트 이력" })); await expect(await canvas.findByText("매장 적립 조건 적용")).toBeVisible(); } };
export const GlobalHistory: Story = { args: { storeId: undefined }, parameters: { msw: { handlers: [http.get("/api/v1/operations/policies/ordinary-point-accrual/global/versions", () => HttpResponse.json({ items: [{ ...version, scopeType: "GLOBAL" }], page: { nextCursor: null } }))] } }, play: async ({ canvas }) => { await userEvent.selectOptions(canvas.getByLabelText("포인트 이력 조회 사유"), "POLICY_AUDIT_REVIEW"); await userEvent.click(canvas.getByRole("button", { name: "포인트 변경 이력 조회" })); await expect(await canvas.findByText("매장 적립 조건 적용")).toBeVisible(); } };
export const Unavailable: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/policies/ordinary-point-accrual/stores/:storeId/versions", () => HttpResponse.json({ code: "DEPENDENCY_UNAVAILABLE" }, { status: 503 }))] } }, play: async ({ canvas }) => { await userEvent.selectOptions(canvas.getByLabelText("포인트 이력 조회 사유"), "POLICY_AUDIT_REVIEW"); await userEvent.click(canvas.getByRole("button", { name: "포인트 변경 이력 조회" })); await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByText("변경 이력이 없습니다")).not.toBeInTheDocument(); } };
