import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent } from "storybook/test";
import { http, HttpResponse } from "msw";
import MockDate from "mockdate";
import { PointAccountWorkspace } from "./PointAccountWorkspace";
const accountId = "96000000-0000-4000-8000-000000000001";
const initial = { accountId, availablePointsKrw: 12500, recoveryPendingKrw: 1500, currency: "KRW" };
const transaction = { transactionId: "96000000-0000-4000-8000-000000000002", type: "ADJUSTMENT", amountKrw: -500, occurredAt: "2026-09-11T00:00:00Z", sourceReference: "point-adjustment:review-001" };
let account = initial;
let key: string | null = null;
const handlers = [http.get("/api/v1/operations/point-accounts/:id", ({ request }) => { expect(request.headers.get("X-Access-Reason")).toBe("POINT_ACCOUNT_INVESTIGATION"); return HttpResponse.json(account); }), http.get("/api/v1/operations/point-accounts/:id/transactions", ({ request }) => { expect(request.headers.get("X-Access-Reason")).toBe("POINT_ACCOUNT_INVESTIGATION"); return HttpResponse.json({ items: [transaction], page: {} }); }), http.post("/api/v1/operations/point-accounts/:id/adjustments", async ({ request }) => { const body = await request.json() as { amountKrw: number; issuer?: unknown; expiresAt?: string }; expect(request.headers.get("Idempotency-Key")).toBeTruthy(); if (body.amountKrw > 0) { expect(body.issuer).toEqual({ issuerType: "BRAND", issuerReference: "brand:reviewed-owner" }); expect(body.expiresAt).toBe("2027-09-10T15:00:00.000Z"); } else { expect(body).not.toHaveProperty("issuer"); expect(body).not.toHaveProperty("expiresAt"); } expect(body).toMatchObject({ reason: "확인된 포인트 차이 조정", evidenceReferences: ["support-case://point-review-001"] }); account = { ...initial, availablePointsKrw: initial.availablePointsKrw + body.amountKrw }; return HttpResponse.json({ account, transactions: [{ ...transaction, amountKrw: body.amountKrw }] }, { status: 201 }); })];
const meta = { title: "Patterns/Operations/Point account", component: PointAccountWorkspace, tags: ["autodocs"], beforeEach: () => { MockDate.set("2026-09-11T00:00:00Z"); account = initial; key = null; return () => MockDate.reset(); }, parameters: { a11y: { test: "error" }, msw: { handlers }, docs: { description: { component: "감사 사유를 가진 포인트 계정/내역 조회와 명시적 issuer·만료·증빙을 가진 signed 조정입니다. 조회 오류는 잔액 0으로 대체하지 않습니다." }, story: { inline: false, height: "1150px" } } } } satisfies Meta<typeof PointAccountWorkspace>;
export default meta; type Story = StoryObj<typeof meta>;
async function read(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"]) { await userEvent.type(canvas.getByLabelText("포인트 계정 ID"), accountId); await userEvent.selectOptions(canvas.getByLabelText("포인트 계정 조회 사유"), "POINT_ACCOUNT_INVESTIGATION"); await userEvent.click(canvas.getByRole("button", { name: "포인트 계정 조회" })); await canvas.findByLabelText("조정 포인트"); }
async function fill(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"], amount: string) { await read(canvas); await userEvent.type(canvas.getByLabelText("조정 포인트"), amount); if (Number(amount) > 0) { await userEvent.selectOptions(canvas.getByLabelText("추가 포인트 비용 주체"), "BRAND"); await userEvent.type(canvas.getByLabelText("추가 포인트 비용 주체 식별값"), "brand:reviewed-owner"); await userEvent.type(canvas.getByLabelText("추가 포인트 만료 (한국 시간)"), "2027-09-11T00:00"); } await userEvent.type(canvas.getByLabelText("포인트 조정 사유"), "확인된 포인트 차이 조정"); await userEvent.type(canvas.getByLabelText("포인트 조정 증빙 위치"), "support-case://point-review-001"); }
export const Credit: Story = { play: async ({ canvas }) => { await fill(canvas, "3000"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("포인트 조정을 적용했습니다")).toBeVisible(); await expect(await canvas.findByText("15,500P")).toBeVisible(); await expect(canvas.getByText("1,500P")).toBeVisible(); } };
export const Debit: Story = { play: async ({ canvas }) => { await fill(canvas, "-500"); await expect(canvas.queryByLabelText("추가 포인트 비용 주체")).not.toBeInTheDocument(); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("12,000P")).toBeVisible(); await expect(canvas.getAllByText("-500P").length).toBeGreaterThan(0); } };
export const InsufficientAvailable: Story = { parameters: { msw: { handlers: [http.post("/api/v1/operations/point-accounts/:id/adjustments", () => HttpResponse.json({ code: "POINT_ADJUSTMENT_INSUFFICIENT_AVAILABLE", correlationId: "POINT-INSUFFICIENT" }, { status: 409 })), ...handlers] } }, play: async ({ canvas }) => { await fill(canvas, "-13000"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("문의 코드 POINT-INSUFFICIENT")).toBeVisible(); await expect(await canvas.findByText("12,500P")).toBeVisible(); } };
export const LostResponse: Story = { parameters: { msw: { handlers: [http.post("/api/v1/operations/point-accounts/:id/adjustments", ({ request }) => { if (!key) { key = request.headers.get("Idempotency-Key"); return HttpResponse.error(); } expect(request.headers.get("Idempotency-Key")).toBe(key); return HttpResponse.json({ account, transactions: [transaction] }, { status: 201 }); }), ...handlers] } }, play: async ({ canvas }) => { await fill(canvas, "-500"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByRole("alert")).toBeVisible(); await userEvent.click(await canvas.findByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("포인트 조정을 적용했습니다")).toBeVisible(); } };
export const Pagination: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/point-accounts/:id/transactions", ({ request }) => new URL(request.url).searchParams.has("cursor") ? HttpResponse.json({ items: [{ ...transaction, amountKrw: 100, sourceReference: "older-adjustment" }], page: {} }) : HttpResponse.json({ items: [transaction], page: { nextCursor: "next" } })), ...handlers] } }, play: async ({ canvas }) => { await read(canvas); await userEvent.click(canvas.getByRole("button", { name: "다음 포인트 거래" })); await expect(await canvas.findByText("older-adjustment")).toBeVisible(); await userEvent.click(canvas.getByRole("button", { name: "이전 포인트 거래" })); await expect(await canvas.findByText(transaction.sourceReference)).toBeVisible(); } };
export const Unavailable: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/point-accounts/:id", () => HttpResponse.json({ code: "DEPENDENCY_UNAVAILABLE" }, { status: 503 })), ...handlers] } }, play: async ({ canvas }) => { await userEvent.type(canvas.getByLabelText("포인트 계정 ID"), accountId); await userEvent.selectOptions(canvas.getByLabelText("포인트 계정 조회 사유"), "POINT_ACCOUNT_INVESTIGATION"); await userEvent.click(canvas.getByRole("button", { name: "포인트 계정 조회" })); await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByLabelText("조정 포인트")).not.toBeInTheDocument(); await expect(canvas.queryByText("0P")).not.toBeInTheDocument(); } };

export const ExplicitIssuerRequired: Story = { play: async ({ canvas }) => { await read(canvas); await userEvent.type(canvas.getByLabelText("조정 포인트"), "3000"); await expect(canvas.getByLabelText("추가 포인트 비용 주체")).toHaveValue(""); await expect(canvas.getByLabelText("추가 포인트 만료 (한국 시간)")).toHaveValue(""); await expect(canvas.getByRole("button", { name: "포인트 조정 적용" })).toBeDisabled(); } };
export const ExpiredCredit: Story = { play: async ({ canvas }) => { await fill(canvas, "3000"); await userEvent.clear(canvas.getByLabelText("추가 포인트 만료 (한국 시간)")); await userEvent.type(canvas.getByLabelText("추가 포인트 만료 (한국 시간)"), "2026-09-10T00:00"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("비용 주체와 미래의 만료 시각을 입력해 주세요.")).toBeVisible(); await expect(canvas.queryByText("포인트 조정을 적용했습니다")).not.toBeInTheDocument(); } };
export const DebitAfterCreditEntry: Story = { play: async ({ canvas }) => { await fill(canvas, "3000"); await userEvent.clear(canvas.getByLabelText("조정 포인트")); await userEvent.type(canvas.getByLabelText("조정 포인트"), "-500"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("12,000P")).toBeVisible(); } };
