import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor } from "storybook/test";
import { http, HttpResponse, delay } from "msw";
import MockDate from "mockdate";
import { PointAccountWorkspace } from "./PointAccountWorkspace";
const accountId = "96000000-0000-4000-8000-000000000001";
const customerId = "97000000-0000-4000-8000-000000000001";
const customer = { customerId, maskedLoginId: "m***", maskedDisplayName: "김*수" };
const initial = { accountId, availablePointsKrw: 12500, recoveryPendingKrw: 1500, currency: "KRW" };
const transaction = { transactionId: "96000000-0000-4000-8000-000000000002", type: "ADJUSTMENT", amountKrw: -500, occurredAt: "2026-09-11T00:00:00Z", sourceReference: "point-adjustment:review-001" };
let account = initial;
let key: string | null = null;
const handlers = [http.get("/api/v1/operations/point-cost-issuers", () => HttpResponse.json({ items: [{ issuerType: "BRAND", issuerReference: "81000000-0000-4000-8000-000000000001", displayName: "검토된 비용 부담 브랜드", source: "BRAND_PROFILE", sourcePolicyVersion: null }], nextCursor: null, canRegisterPlatform: false })), http.post("/api/v1/operations/customer-searches", async ({ request }) => { expect(await request.json()).toEqual({ loginId: "minsu01", reasonCode: "POINT_ACCOUNT_INVESTIGATION" }); return HttpResponse.json({ items: [customer] }); }), http.get("/api/v1/operations/customers/:customerId/point-account", ({ params, request }) => { expect(params.customerId).toBe(customerId); expect(request.headers.get("X-Access-Reason")).toBe("POINT_ACCOUNT_INVESTIGATION"); return HttpResponse.json({ customerId, accountId }); }),http.get("/api/v1/operations/point-accounts/:id", ({ request }) => { expect(request.headers.get("X-Access-Reason")).toBe("POINT_ACCOUNT_INVESTIGATION"); return HttpResponse.json(account); }), http.get("/api/v1/operations/point-accounts/:id/transactions", ({ request }) => { expect(request.headers.get("X-Access-Reason")).toBe("POINT_ACCOUNT_INVESTIGATION"); return HttpResponse.json({ items: [transaction], page: {} }); }), http.post("/api/v1/operations/point-accounts/:id/adjustments", async ({ request }) => { const body = await request.json() as { amountKrw: number; issuer?: unknown; expiresAt?: string }; expect(request.headers.get("Idempotency-Key")).toBeTruthy(); if (body.amountKrw > 0) { expect(body.issuer).toEqual({ issuerType: "BRAND", issuerReference: "81000000-0000-4000-8000-000000000001" }); expect(body.expiresAt).toBe("2027-09-10T15:00:00.000Z"); } else { expect(body).not.toHaveProperty("issuer"); expect(body).not.toHaveProperty("expiresAt"); } expect(body).toMatchObject({ reason: "확인된 포인트 차이 조정", evidenceReferences: ["support-case://point-review-001"] }); account = { ...initial, availablePointsKrw: initial.availablePointsKrw + body.amountKrw }; return HttpResponse.json({ account, transactions: [{ ...transaction, amountKrw: body.amountKrw }] }, { status: 201 }); })];
const meta = { title: "Patterns/Operations/Point account", component: PointAccountWorkspace, tags: ["autodocs"], beforeEach: () => { MockDate.set("2026-09-11T00:00:00Z"); account = initial; key = null; return () => MockDate.reset(); }, parameters: { a11y: { test: "error" }, msw: { handlers }, docs: { description: { component: "가입 고객을 검색·선택해 계정 ID 입력 없이 조회하고, 명시적 issuer·만료·증빙을 가진 signed 조정입니다. 조회 오류는 잔액 0으로 대체하지 않습니다." }, story: { inline: false, height: "1150px" } } } } satisfies Meta<typeof PointAccountWorkspace>;
export default meta; type Story = StoryObj<typeof meta>;
async function selectCustomer(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"]) { await userEvent.type(canvas.getByLabelText("고객 로그인 아이디"), "minsu01"); await userEvent.click(canvas.getByRole("button", { name: "고객 찾기" })); await userEvent.click(await canvas.findByRole("button", { name: "이 고객 선택" })); }
async function read(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"]) { await selectCustomer(canvas); await canvas.findByLabelText("조정 포인트"); }
async function fill(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"], amount: string) { await read(canvas); await userEvent.type(canvas.getByLabelText("조정 포인트"), amount); if (Number(amount) > 0) { await userEvent.selectOptions(canvas.getByLabelText("추가 포인트 비용 주체"), "BRAND"); await userEvent.click(await canvas.findByRole("button", { name: "검토된 비용 부담 브랜드 선택" })); await userEvent.type(canvas.getByLabelText("추가 포인트 만료 (한국 시간)"), "2027-09-11T00:00"); } await userEvent.type(canvas.getByLabelText("포인트 조정 사유"), "확인된 포인트 차이 조정"); await userEvent.type(canvas.getByLabelText("포인트 조정 증빙 위치"), "support-case://point-review-001"); }
export const Credit: Story = { play: async ({ canvas }) => { await fill(canvas, "3000"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("포인트 조정을 적용했습니다")).toBeVisible(); await expect(await canvas.findByText("15,500P")).toBeVisible(); await expect(canvas.getByText("1,500P")).toBeVisible(); } };
export const Debit: Story = { play: async ({ canvas }) => { await fill(canvas, "-500"); await expect(canvas.queryByLabelText("추가 포인트 비용 주체")).not.toBeInTheDocument(); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("12,000P")).toBeVisible(); await expect(canvas.getAllByText("-500P").length).toBeGreaterThan(0); } };
export const InsufficientAvailable: Story = { parameters: { msw: { handlers: [http.post("/api/v1/operations/point-accounts/:id/adjustments", () => HttpResponse.json({ code: "POINT_ADJUSTMENT_INSUFFICIENT_AVAILABLE", correlationId: "POINT-INSUFFICIENT" }, { status: 409 })), ...handlers] } }, play: async ({ canvas }) => { await fill(canvas, "-13000"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("문의 코드 POINT-INSUFFICIENT")).toBeVisible(); await expect(await canvas.findByText("12,500P")).toBeVisible(); } };
export const LostResponse: Story = { parameters: { msw: { handlers: [http.post("/api/v1/operations/point-accounts/:id/adjustments", ({ request }) => { if (!key) { key = request.headers.get("Idempotency-Key"); return HttpResponse.error(); } expect(request.headers.get("Idempotency-Key")).toBe(key); return HttpResponse.json({ account, transactions: [transaction] }, { status: 201 }); }), ...handlers] } }, play: async ({ canvas }) => { await fill(canvas, "-500"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.getByRole("button", { name: "다른 고객 찾기" })).toBeDisabled(); await expect(canvas.getByLabelText("조정 포인트")).toBeDisabled(); await userEvent.click(await canvas.findByRole("button", { name: "같은 요청으로 결과 확인" })); await expect(await canvas.findByText("포인트 조정을 적용했습니다")).toBeVisible(); } };
export const Pagination: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/point-accounts/:id/transactions", ({ request }) => new URL(request.url).searchParams.has("cursor") ? HttpResponse.json({ items: [{ ...transaction, amountKrw: 100, sourceReference: "older-adjustment" }], page: {} }) : HttpResponse.json({ items: [transaction], page: { nextCursor: "next" } })), ...handlers] } }, play: async ({ canvas }) => { await read(canvas); await userEvent.click(canvas.getByRole("button", { name: "다음 포인트 거래" })); await expect(await canvas.findByText("older-adjustment")).toBeVisible(); await userEvent.click(canvas.getByRole("button", { name: "이전 포인트 거래" })); await expect(await canvas.findByText(transaction.sourceReference)).toBeVisible(); } };
export const Unavailable: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/point-accounts/:id", () => HttpResponse.json({ code: "DEPENDENCY_UNAVAILABLE" }, { status: 503 })), ...handlers] } }, play: async ({ canvas }) => { await selectCustomer(canvas); await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByLabelText("조정 포인트")).not.toBeInTheDocument(); await expect(canvas.queryByText("0P")).not.toBeInTheDocument(); } };

export const ExplicitIssuerRequired: Story = { play: async ({ canvas }) => { await read(canvas); await userEvent.type(canvas.getByLabelText("조정 포인트"), "3000"); await expect(canvas.getByLabelText("추가 포인트 비용 주체")).toHaveValue(""); await expect(canvas.getByLabelText("추가 포인트 만료 (한국 시간)")).toHaveValue(""); await expect(canvas.getByRole("button", { name: "포인트 조정 적용" })).toBeDisabled(); } };
export const ExpiredCredit: Story = { play: async ({ canvas }) => { await fill(canvas, "3000"); await userEvent.clear(canvas.getByLabelText("추가 포인트 만료 (한국 시간)")); await userEvent.type(canvas.getByLabelText("추가 포인트 만료 (한국 시간)"), "2026-09-10T00:00"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("비용 주체와 미래의 만료 시각을 입력해 주세요.")).toBeVisible(); await expect(canvas.queryByText("포인트 조정을 적용했습니다")).not.toBeInTheDocument(); } };
export const DebitAfterCreditEntry: Story = { play: async ({ canvas }) => { await fill(canvas, "3000"); await userEvent.clear(canvas.getByLabelText("조정 포인트")); await userEvent.type(canvas.getByLabelText("조정 포인트"), "-500"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("12,000P")).toBeVisible(); } };

export const ResolveUnavailable: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/customers/:customerId/point-account", () => HttpResponse.json({ code: "POINT_ACCOUNT_INTEGRITY_FAILURE", correlationId: "POINT-MISSING" }, { status: 503 })), ...handlers] } }, play: async ({ canvas }) => { await selectCustomer(canvas); await expect(await canvas.findByText("문의 코드 POINT-MISSING")).toBeVisible(); await expect(canvas.queryByLabelText("조정 포인트")).not.toBeInTheDocument(); await expect(canvas.queryByText("0P")).not.toBeInTheDocument(); await expect(canvas.getByRole("button", { name: "다른 고객 찾기" })).toBeEnabled(); } };
export const ResolveDenied: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/customers/:customerId/point-account", () => HttpResponse.json({ code: "ACCESS_DENIED", correlationId: "POINT-READ-DENIED" }, { status: 403 })), ...handlers] } }, play: async ({ canvas }) => { await selectCustomer(canvas); await expect(await canvas.findByText("문의 코드 POINT-READ-DENIED")).toBeVisible(); await expect(canvas.queryByLabelText("조정 포인트")).not.toBeInTheDocument(); } };
export const ResolveLoading: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/customers/:customerId/point-account", async () => { await delay("infinite"); return HttpResponse.json({ customerId, accountId }); }), ...handlers] } }, play: async ({ canvas }) => { await selectCustomer(canvas); await expect(await canvas.findByText("선택한 고객의 포인트 계정을 연결하는 중")).toBeVisible(); await expect(canvas.queryByLabelText("조정 포인트")).not.toBeInTheDocument(); } };
export const AdjustmentPending: Story = { parameters: { msw: { handlers: [http.post("/api/v1/operations/point-accounts/:id/adjustments", async () => { await delay("infinite"); return HttpResponse.json({ account, transactions: [transaction] }); }), ...handlers] } }, play: async ({ canvas }) => { await fill(canvas, "-500"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(canvas.getByRole("button", { name: "다른 고객 찾기" })).toBeDisabled(); await expect(canvas.getByLabelText("조정 포인트")).toBeDisabled(); await expect(canvas.getByRole("button", { name: "포인트 조정 적용" })).toBeDisabled(); } };
export const CustomerChangeClearsDetails: Story = { play: async ({ canvas }) => { await fill(canvas, "3000"); await userEvent.click(canvas.getByRole("button", { name: "다른 고객 찾기" })); await expect(canvas.queryByText("12,500P")).not.toBeInTheDocument(); await expect(canvas.queryByText(transaction.sourceReference)).not.toBeInTheDocument(); await expect(canvas.queryByLabelText("조정 포인트")).not.toBeInTheDocument(); await read(canvas); await expect(canvas.getByLabelText("조정 포인트")).toHaveValue(null); await expect(canvas.getByLabelText("포인트 조정 사유")).toHaveValue(""); await expect(canvas.getByLabelText("포인트 조정 증빙 위치")).toHaveValue(""); } };
let releaseResolution: (() => void) | undefined;
export const LateResolutionIgnored: Story = { beforeEach: () => { releaseResolution = undefined; }, parameters: { msw: { handlers: [http.get("/api/v1/operations/customers/:customerId/point-account", async () => { await new Promise<void>(resolve => { releaseResolution = resolve; }); return HttpResponse.json({ customerId, accountId }); }), ...handlers] } }, play: async ({ canvas }) => { await selectCustomer(canvas); await waitFor(() => expect(typeof releaseResolution).toBe("function")); await userEvent.click(canvas.getByRole("button", { name: "다른 고객 찾기" })); releaseResolution?.(); await expect(canvas.getByLabelText("고객 로그인 아이디")).toBeVisible(); await expect(canvas.queryByText("현재 포인트")).not.toBeInTheDocument(); await expect(canvas.queryByLabelText("조정 포인트")).not.toBeInTheDocument(); } };
let adjustmentCalls = 0;
let frozenPayload: unknown;
export const RetryDenialKeepsOriginalIntent: Story = { beforeEach: () => { adjustmentCalls = 0; frozenPayload = undefined; }, parameters: { msw: { handlers: [http.post("/api/v1/operations/point-accounts/:id/adjustments", async ({ request, params }) => { expect(params.id).toBe(accountId); const body = await request.json(); adjustmentCalls++; if (adjustmentCalls === 1) { key = request.headers.get("Idempotency-Key"); frozenPayload = body; return HttpResponse.json({ code: "DEPENDENCY_UNAVAILABLE" }, { status: 503 }); } expect(request.headers.get("Idempotency-Key")).toBe(key); expect(body).toEqual(frozenPayload); if (adjustmentCalls === 2) return HttpResponse.json({ code: "ACCESS_DENIED", correlationId: "RETRY-DENIED" }, { status: 403 }); return HttpResponse.json({ account, transactions: [transaction] }, { status: 201 }); }), ...handlers] } }, play: async ({ canvas }) => { await fill(canvas, "-500"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await userEvent.click(await canvas.findByRole("button", { name: "같은 요청으로 결과 확인" })); await expect(await canvas.findByText("문의 코드 RETRY-DENIED")).toBeVisible(); await expect(canvas.getByRole("button", { name: "다른 고객 찾기" })).toBeDisabled(); await expect(canvas.getByLabelText("조정 포인트")).toBeDisabled(); await userEvent.click(canvas.getByRole("button", { name: "같은 요청으로 결과 확인" })); await expect(await canvas.findByText("포인트 조정을 적용했습니다")).toBeVisible(); await expect(canvas.getByRole("button", { name: "다른 고객 찾기" })).toBeEnabled(); } };
let summaryCalls = 0;
export const RefreshFailureBlocksNewAdjustment: Story = { beforeEach: () => { summaryCalls = 0; }, parameters: { msw: { handlers: [http.get("/api/v1/operations/point-accounts/:id", () => { summaryCalls++; return summaryCalls === 1 ? HttpResponse.json(account) : HttpResponse.json({ code: "DEPENDENCY_UNAVAILABLE", correlationId: "REFRESH-FAILED" }, { status: 503 }); }), ...handlers] } }, play: async ({ canvas }) => { await fill(canvas, "-500"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("포인트 조정을 적용했습니다")).toBeVisible(); await expect(await canvas.findByText("문의 코드 REFRESH-FAILED")).toBeVisible(); await expect(canvas.queryByLabelText("조정 포인트")).not.toBeInTheDocument(); await expect(canvas.queryByText("12,500P")).not.toBeInTheDocument(); } };
export const MemoryOnlySelection: Story = { play: async ({ canvas }) => { const localBefore = JSON.stringify(localStorage); const sessionBefore = JSON.stringify(sessionStorage); await read(canvas); await expect(JSON.stringify(localStorage)).toBe(localBefore); await expect(JSON.stringify(sessionStorage)).toBe(sessionBefore); await expect(window.location.href).not.toContain(customerId); await expect(window.location.href).not.toContain(accountId); } };

const secondCustomer = { customerId: "97000000-0000-4000-8000-000000000002", maskedLoginId: "o***", maskedDisplayName: "이*진" };
const secondAccount = "96000000-0000-4000-8000-000000000009";
let releaseOldReads: Array<() => void> = [];
export const LateCustomerReadsIgnored: Story = { beforeEach: () => { releaseOldReads = []; }, parameters: { msw: { handlers: [
  http.post("/api/v1/operations/customer-searches", async ({ request }) => { const body = await request.json() as { loginId: string }; return HttpResponse.json({ items: [body.loginId === "other01" ? secondCustomer : customer] }); }),
  http.get("/api/v1/operations/customers/:customerId/point-account", ({ params }) => HttpResponse.json(params.customerId === secondCustomer.customerId ? { customerId: secondCustomer.customerId, accountId: secondAccount } : { customerId, accountId })),
  http.get("/api/v1/operations/point-accounts/:id", async ({ params }) => { if (params.id === accountId) { await new Promise<void>(resolve => releaseOldReads.push(resolve)); return HttpResponse.json(initial); } return HttpResponse.json({ ...initial, accountId: secondAccount, availablePointsKrw: 700 }); }),
  http.get("/api/v1/operations/point-accounts/:id/transactions", async ({ params }) => { if (params.id === accountId) { await new Promise<void>(resolve => releaseOldReads.push(resolve)); return HttpResponse.json({ items: [transaction], page: { nextCursor: "old-customer-cursor" } }); } return HttpResponse.json({ items: [], page: {} }); }),
  ...handlers,
] } }, play: async ({ canvas }) => {
  await selectCustomer(canvas); await waitFor(() => expect(releaseOldReads).toHaveLength(2));
  await userEvent.click(canvas.getByRole("button", { name: "다른 고객 찾기" }));
  await userEvent.type(canvas.getByLabelText("고객 로그인 아이디"), "other01"); await userEvent.click(canvas.getByRole("button", { name: "고객 찾기" }));
  await userEvent.click(await canvas.findByRole("button", { name: "이 고객 선택" }));
  await expect(await canvas.findByText("700P")).toBeVisible();
  releaseOldReads.forEach(resolve => resolve());
  await userEvent.type(await canvas.findByLabelText("포인트 조정 사유"), "새 고객 확인");
  await expect(canvas.getByText("700P")).toBeVisible(); await expect(canvas.queryByText("12,500P")).not.toBeInTheDocument();
  await expect(canvas.queryByText(transaction.sourceReference)).not.toBeInTheDocument(); await expect(canvas.getByRole("button", { name: "다음 포인트 거래" })).toBeDisabled();
} };

export const UncertainAdjustment: Story = { parameters: { msw: { handlers: [http.post("/api/v1/operations/point-accounts/:id/adjustments", () => HttpResponse.json({ code: "DEPENDENCY_UNAVAILABLE", correlationId: "POINT-RESULT-UNKNOWN" }, { status: 503 })), ...handlers] } }, play: async ({ canvas }) => { await fill(canvas, "-500"); await userEvent.click(canvas.getByRole("button", { name: "포인트 조정 적용" })); await expect(await canvas.findByText("포인트 조정 결과를 확인해야 합니다")).toBeVisible(); await expect(canvas.getByRole("button", { name: "다른 고객 찾기" })).toBeDisabled(); await expect(canvas.getByLabelText("조정 포인트")).toBeDisabled(); await expect(canvas.getByRole("button", { name: "같은 요청으로 결과 확인" })).toBeEnabled(); await expect(canvas.queryByText("포인트 조정을 적용했습니다")).not.toBeInTheDocument(); } };
