import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent } from "storybook/test";
import { http, HttpResponse } from "msw";
import { ids } from "../../../.storybook/fixtures";
import { StoreMembershipsWorkspace } from "./StoreMembershipsWorkspace";

const original = { accountDisplayName: "성수점 점주", accountLoginId: "owner01", membershipId: "96000000-0000-4000-8000-000000000001", accountId: "96000000-0000-4000-8000-000000000002", storeId: ids.store, role: "OWNER", status: "ACTIVE", version: 1, createdAt: "2026-10-01T00:00:00Z", updatedAt: "2026-10-01T00:00:00Z" };
let current = { ...original };
const handlers = [
  http.get("/api/v1/operations/stores/:storeId/memberships/account-target", ({ request }) => { expect(request.headers.get("X-Access-Reason")).toBeTruthy(); return HttpResponse.json({ accountId: "96000000-0000-4000-8000-000000000003", loginId: "staff01", displayName: "신규 직원" }); }),
  http.get("/api/v1/operations/stores/:storeId/memberships", () => HttpResponse.json({ items: [current], nextCursor: null })),
  http.get("/api/v1/operations/stores/:storeId/memberships/:accountId", () => HttpResponse.json(current)),

  http.post("/api/v1/operations/stores/:storeId/memberships", async ({ request }) => { const body = await request.json() as typeof original; expect(body.accountId).toBe("96000000-0000-4000-8000-000000000003"); current = { ...original, ...body }; return HttpResponse.json(current, { status: 201 }); }),
  http.put("/api/v1/operations/stores/:storeId/memberships/:accountId", async ({ request }) => { const body = await request.json() as typeof original & { expectedVersion: number }; expect(body.expectedVersion).toBe(current.version); if (body.status === "REVOKED") expect(body.role).toBe(current.role); current = { ...current, ...body, version: current.version + 1 }; return HttpResponse.json(current); }),
];
const meta = { title: "Patterns/Operations/Store memberships", component: StoreMembershipsWorkspace, tags: ["autodocs"], args: { storeId: ids.store }, beforeEach: () => { current = { ...original }; }, parameters: { a11y: { test: "error" }, msw: { handlers }, docs: { story: { inline: false, height: "1000px" }, description: { component: "현재 매장 소속을 조회해 역할 변경·철회·재활성화하고 기존 점주 계정을 조회해 새 소속을 부여합니다. 계정 비밀번호와 인증 상태는 변경하지 않습니다." } } } } satisfies Meta<typeof StoreMembershipsWorkspace>;
export default meta; type Story = StoryObj<typeof meta>;
async function edit(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"]) { await userEvent.click(await canvas.findByRole("button", { name: `${original.accountDisplayName} (${original.accountLoginId}) 소속 변경` })); await expect(await canvas.findByLabelText("소속 상태")).toHaveValue("ACTIVE"); }
export const RevokeMembership: Story = { play: async ({ canvas }) => { await edit(canvas); await userEvent.selectOptions(canvas.getByLabelText("소속 상태"), "REVOKED"); await expect(canvas.getByLabelText("매장 역할")).toBeDisabled(); await userEvent.type(canvas.getByLabelText("소속 변경 사유"), "계약 종료 확인"); await userEvent.click(canvas.getByRole("button", { name: "소속 변경 저장" })); await expect(await canvas.findByText("소속을 변경했습니다.")).toBeVisible(); await expect(await canvas.findByText("철회됨")).toBeVisible(); } };
export const AddExistingAccount: Story = { play: async ({ canvas }) => { await userEvent.click(await canvas.findByRole("button", { name: "기존 계정에 소속 추가" })); await userEvent.type(canvas.getByLabelText("추가할 계정 로그인 ID"), "staff01"); await userEvent.selectOptions(canvas.getByLabelText("계정 조회 사유"), "STORE_MEMBERSHIP_ASSIGNMENT_REVIEW"); await userEvent.click(canvas.getByRole("button", { name: "소속 추가 대상 조회" })); await expect(await canvas.findByText("신규 직원 · staff01")).toBeVisible(); await userEvent.selectOptions(canvas.getByLabelText("매장 역할"), "STAFF"); await userEvent.type(canvas.getByLabelText("소속 추가 사유"), "신규 직원 배정"); await userEvent.click(canvas.getByRole("button", { name: "매장 소속 추가" })); await expect(await canvas.findByText("기존 계정에 매장 소속을 추가했습니다.")).toBeVisible(); } };
export const Reactivate: Story = { beforeEach: () => { current = { ...original, status: "REVOKED" }; }, play: async ({ canvas }) => { await userEvent.click(await canvas.findByRole("button", { name: `${original.accountDisplayName} (${original.accountLoginId}) 소속 변경` })); await userEvent.selectOptions(await canvas.findByLabelText("소속 상태"), "ACTIVE"); await userEvent.selectOptions(canvas.getByLabelText("매장 역할"), "STAFF"); await userEvent.type(canvas.getByLabelText("소속 변경 사유"), "직원 역할로 재배정"); await userEvent.click(canvas.getByRole("button", { name: "소속 변경 저장" })); await expect(await canvas.findByText("소속을 변경했습니다.")).toBeVisible(); await expect(await canvas.findByText("직원")).toBeVisible(); } };
export const Conflict: Story = { parameters: { msw: { handlers: [http.put("/api/v1/operations/stores/:storeId/memberships/:accountId", () => HttpResponse.json({ code: "RESOURCE_STATE_CONFLICT", correlationId: "MEMBERSHIP-CONFLICT" }, { status: 409 })), ...handlers] } }, play: async ({ canvas }) => { await edit(canvas); await userEvent.selectOptions(canvas.getByLabelText("매장 역할"), "STAFF"); await userEvent.type(canvas.getByLabelText("소속 변경 사유"), "역할 변경"); await userEvent.click(canvas.getByRole("button", { name: "소속 변경 저장" })); await expect(await canvas.findByText("문의 코드 MEMBERSHIP-CONFLICT")).toBeVisible(); } };
export const Forbidden: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/stores/:storeId/memberships", () => HttpResponse.json({ code: "ACCESS_DENIED" }, { status: 403 }))] } }, play: async ({ canvas }) => { await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "기존 계정에 소속 추가" })).not.toBeInTheDocument(); } };

export const MembershipPagination: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/stores/:storeId/memberships", ({ request }) => new URL(request.url).searchParams.has("cursor") ? HttpResponse.json({ items: [{ ...original, role: "STAFF" }], nextCursor: null }) : HttpResponse.json({ items: [original], nextCursor: "memberships-next" })), ...handlers] } }, play: async ({ canvas }) => { await userEvent.click(await canvas.findByRole("button", { name: "다음 소속 목록" })); await expect(await canvas.findByText("직원")).toBeVisible(); await userEvent.click(canvas.getByRole("button", { name: "이전 소속 목록" })); await expect(await canvas.findByText("점주")).toBeVisible(); } };

export const MissingAccountLabel: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/stores/:storeId/memberships", () => HttpResponse.json({ items: [{ ...original, accountDisplayName: null }], nextCursor: null }))] } }, play: async ({ canvas }) => { await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByText(original.accountId)).not.toBeInTheDocument(); } };

export const MembershipWriteOnly: Story = {
  args: { mode: "add" },
  parameters: { msw: { handlers: [http.get("/api/v1/operations/merchant-accounts", () => { throw new Error("Credential read must not be requested"); }), http.get("/api/v1/operations/stores/:storeId/memberships", () => { throw new Error("Membership list read must not be requested"); }), ...handlers] } },
  play: async ({ canvas }) => { await userEvent.type(canvas.getByLabelText("추가할 계정 로그인 ID"), "staff01"); await userEvent.selectOptions(canvas.getByLabelText("계정 조회 사유"), "STORE_MEMBERSHIP_ASSIGNMENT_REVIEW"); await userEvent.click(canvas.getByRole("button", { name: "소속 추가 대상 조회" })); await expect(await canvas.findByText("신규 직원 · staff01")).toBeVisible(); await userEvent.type(canvas.getByLabelText("소속 추가 사유"), "직원 소속 추가"); await userEvent.click(canvas.getByRole("button", { name: "매장 소속 추가" })); await expect(await canvas.findByText("기존 계정에 매장 소속을 추가했습니다.")).toBeVisible(); },
};
