import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent } from "storybook/test";
import { http, HttpResponse } from "msw";
import { ids } from "../../../.storybook/fixtures";
import { StorePointPolicyDirectory } from "./StorePointPolicyDirectory";

const first = { policyVersionId: 12, scopeType: "STORE", scopeReference: ids.store, state: "INHERIT_GLOBAL", effectiveAt: "2026-09-11T00:00:00Z", actorType: "PLATFORM_OPERATOR", actorReference: "operator-1", reason: "공통 상속" };
const handler = http.get("/api/v1/operations/policies/ordinary-point-accrual/stores", ({ request }) => { expect(request.headers.get("X-Access-Reason")).toBe("POLICY_AUDIT_REVIEW"); const q = new URL(request.url).searchParams; return HttpResponse.json(q.has("cursor") ? { items: [{ ...first, scopeReference: "97000000-0000-4000-8000-000000000001" }], page: { nextCursor: null } } : q.get("state") === "OVERRIDE" ? { items: [], page: { nextCursor: null } } : { items: [first], page: { nextCursor: "store-policy-next" } }); });
const meta = { title: "Patterns/Operations/Store point policy directory", component: StorePointPolicyDirectory, tags: ["autodocs"], parameters: { a11y: { test: "error" }, msw: { handlers: [handler] }, docs: { description: { component: "명시적으로 저장된 매장 포인트 설정을 필터·커서로 찾고 해당 매장의 실제 적용 정책을 조회합니다. 별도 설정이 없는 매장은 확인한 매장 ID로 조회할 수 있습니다." }, story: { inline: false, height: "950px" } } } } satisfies Meta<typeof StorePointPolicyDirectory>;
export default meta; type Story = StoryObj<typeof meta>;
export const FilterAndPage: Story = { play: async ({ canvas }) => { await userEvent.selectOptions(canvas.getByLabelText("매장 정책 목록 조회 사유"), "POLICY_AUDIT_REVIEW"); await userEvent.click(canvas.getByRole("button", { name: "매장 정책 목록 조회" })); await expect(await canvas.findByText(ids.store)).toBeVisible(); await userEvent.click(canvas.getByRole("button", { name: "다음 매장 정책" })); await expect(await canvas.findByText("97000000-0000-4000-8000-000000000001")).toBeVisible(); await userEvent.selectOptions(canvas.getByLabelText("매장 정책 상태"), "OVERRIDE"); await userEvent.click(canvas.getByRole("button", { name: "매장 정책 목록 조회" })); await expect(await canvas.findByText("일치하는 매장 정책이 없습니다")).toBeVisible(); } };
export const SelectStore: Story = { play: async ({ canvas }) => { await userEvent.selectOptions(canvas.getByLabelText("매장 정책 목록 조회 사유"), "POLICY_AUDIT_REVIEW"); await userEvent.click(canvas.getByRole("button", { name: "매장 정책 목록 조회" })); await userEvent.click(await canvas.findByRole("button", { name: `${ids.store} 포인트 관리` })); await expect(await canvas.findByRole("button", { name: "현재 매장 포인트 정책 조회" })).toBeVisible(); } };
export const NoExplicitHead: Story = { play: async ({ canvas }) => { await userEvent.type(canvas.getByLabelText("포인트를 관리할 매장 ID"), ids.store); await userEvent.click(canvas.getByRole("button", { name: "지정 매장 포인트 관리" })); await expect(await canvas.findByRole("button", { name: "현재 매장 포인트 정책 조회" })).toBeVisible(); } };
