import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent } from "storybook/test";
import { http, HttpResponse } from "msw";
import { ids } from "../../../.storybook/fixtures";
import { StorePointPolicyWorkspace } from "./StorePointPolicyWorkspace";

const policy = { policyVersionId: 12, scopeType: "GLOBAL", scopeReference: "d6578ecd-7fe4-5493-92e0-bebde2fbcd13", state: "OVERRIDE", accrualRateBps: 500, roundingMode: "FLOOR", issuerType: "PLATFORM", issuerReference: "platform:beanflow", expiryRule: "SEOUL_CALENDAR_DAYS_FROM_COMPLETION", validityDays: 365, effectiveAt: "2026-09-11T00:00:00Z", actorType: "PLATFORM_OPERATOR", actorReference: "operator-1", reason: "공통 적립 조건" };
let head: typeof policy | null;
let key: string | null;
const current = () => ({ storeId: ids.store, explicitHead: head ?? undefined, selectionSource: !head ? "GLOBAL_NO_OVERRIDE" : head.state === "INHERIT_GLOBAL" ? "GLOBAL_INHERITED" : "STORE_OVERRIDE", effectivePolicy: { ...(!head || head.state === "INHERIT_GLOBAL" ? policy : head), canonicalPolicyHash: "a".repeat(64) } });
const handlers = [
  http.get("/api/v1/operations/policies/ordinary-point-accrual/stores/:storeId", () => HttpResponse.json(current())),
  http.patch("/api/v1/operations/policies/ordinary-point-accrual/stores/:storeId", async ({ request }) => { const body = await request.json() as typeof policy & { expectedPolicyVersionId?: number }; expect(body.expectedPolicyVersionId).toBe(head?.policyVersionId); if (body.state === "INHERIT_GLOBAL") expect(body.accrualRateBps).toBeUndefined(); head = { ...policy, ...body, policyVersionId: 13, scopeType: "STORE", scopeReference: ids.store }; return HttpResponse.json(head); }),
];
const meta = { title: "Patterns/Operations/Store point policy", component: StorePointPolicyWorkspace, tags: ["autodocs"], args: { storeId: ids.store }, beforeEach: () => { head = null; key = null; }, parameters: { a11y: { test: "error" }, msw: { handlers }, docs: { description: { component: "매장의 명시적 설정과 실제 적용 정책을 조회하고 전용 정책 생성·변경 또는 공통 정책 상속을 처리합니다. 적립 비용 주체는 매장이나 브랜드에서 추론하지 않습니다." }, story: { inline: false, height: "1100px" } } } } satisfies Meta<typeof StorePointPolicyWorkspace>;
export default meta; type Story = StoryObj<typeof meta>;
async function load(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"]) { await userEvent.selectOptions(canvas.getByLabelText("매장 포인트 조회 사유"), "POLICY_CHANGE_REVIEW"); await userEvent.click(canvas.getByRole("button", { name: "현재 매장 포인트 정책 조회" })); await expect(await canvas.findByText("실제 적립률 5.00%")).toBeVisible(); }
export const FirstOverride: Story = { play: async ({ canvas }) => { await load(canvas); await expect(canvas.getByText("별도 설정 없이 공통 정책 적용")).toBeVisible(); await userEvent.selectOptions(canvas.getByLabelText("매장 포인트 적용 방식"), "OVERRIDE"); await userEvent.clear(canvas.getByLabelText("매장 적립률 (%)")); await userEvent.type(canvas.getByLabelText("매장 적립률 (%)"), "7"); await userEvent.type(canvas.getByLabelText("매장 포인트 변경 사유"), "매장별 프로모션"); await userEvent.click(canvas.getByRole("button", { name: "매장 포인트 정책 저장" })); await expect(await canvas.findByText("실제 적립률 7.00%")).toBeVisible(); } };
export const RestoreInheritance: Story = { beforeEach: () => { head = { ...policy, scopeType: "STORE", scopeReference: ids.store }; }, play: async ({ canvas }) => { await load(canvas); await userEvent.selectOptions(canvas.getByLabelText("매장 포인트 적용 방식"), "INHERIT_GLOBAL"); await expect(canvas.queryByLabelText("매장 적립률 (%)")).not.toBeInTheDocument(); await userEvent.type(canvas.getByLabelText("매장 포인트 변경 사유"), "공통 적립 정책 복귀"); await userEvent.click(canvas.getByRole("button", { name: "매장 포인트 정책 저장" })); await expect(await canvas.findByText("명시적으로 공통 정책 상속")).toBeVisible(); } };
export const Conflict: Story = { parameters: { msw: { handlers: [http.patch("/api/v1/operations/policies/ordinary-point-accrual/stores/:storeId", () => HttpResponse.json({ code: "POLICY_VERSION_CONFLICT" }, { status: 409 })), ...handlers] } }, play: async ({ canvas }) => { await load(canvas); await userEvent.type(canvas.getByLabelText("매장 포인트 변경 사유"), "명시적 공통 상속"); await userEvent.click(canvas.getByRole("button", { name: "매장 포인트 정책 저장" })); await expect(await canvas.findByText("정책 버전이 변경되었습니다")).toBeVisible(); } };
export const Forbidden: Story = { parameters: { msw: { handlers: [http.get("/api/v1/operations/policies/ordinary-point-accrual/stores/:storeId", () => HttpResponse.json({ code: "ACCESS_DENIED" }, { status: 403 }))] } }, play: async ({ canvas }) => { await userEvent.selectOptions(canvas.getByLabelText("매장 포인트 조회 사유"), "POLICY_CHANGE_REVIEW"); await userEvent.click(canvas.getByRole("button", { name: "현재 매장 포인트 정책 조회" })); await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByText("실제 적립률 0.00%")).not.toBeInTheDocument(); await expect(canvas.queryByRole("button", { name: "매장 포인트 정책 저장" })).not.toBeInTheDocument(); } };
export const LostResponse: Story = { parameters: { msw: { handlers: [http.patch("/api/v1/operations/policies/ordinary-point-accrual/stores/:storeId", async ({ request }) => { if (!key) { key = request.headers.get("Idempotency-Key"); return HttpResponse.error(); } expect(request.headers.get("Idempotency-Key")).toBe(key); head = { ...policy, state: "INHERIT_GLOBAL", scopeType: "STORE", policyVersionId: 13 }; return HttpResponse.json(head); }), ...handlers] } }, play: async ({ canvas }) => { await load(canvas); await userEvent.type(canvas.getByLabelText("매장 포인트 변경 사유"), "공통 정책 상속 확인"); await userEvent.click(canvas.getByRole("button", { name: "매장 포인트 정책 저장" })); await expect(await canvas.findByRole("alert")).toBeVisible(); await userEvent.click(canvas.getByRole("button", { name: "매장 포인트 정책 저장" })); await expect(await canvas.findByText("명시적으로 공통 정책 상속")).toBeVisible(); } };
