package io.github.kdh949.beanflow.shared.api

enum class FailureCode {
    INVALID_REQUEST,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    MENU_CONFIGURATION_NOT_AVAILABLE,
    PICKUP_SLOT_FULL,
    STOCK_NOT_AVAILABLE,
    COUPON_NOT_AVAILABLE,
    POINT_BALANCE_INSUFFICIENT,
    POINT_ADJUSTMENT_INSUFFICIENT_AVAILABLE,
    ORDER_STATE_CONFLICT,
    REORDER_SOURCE_STATE_INVALID,
    REORDER_ITEMS_UNAVAILABLE,
    COMPENSATION_SOURCE_CONFLICT,
    PUBLICATION_TARGET_UNMAPPED,
    IDEMPOTENCY_KEY_REUSED,
    IDEMPOTENCY_REQUEST_IN_PROGRESS,
    IDEMPOTENCY_MANUAL_REVIEW_REQUIRED,
    RESERVATION_EXPIRED,
    PAYMENT_DECLINED,
    PAYMENT_REFUND_UNRESOLVED,
    SETTLEMENT_INPUT_UNAVAILABLE,
    DISPUTE_WINDOW_CLOSED,
    DISPUTE_ALREADY_ACTIVE,
    DISPUTE_REFILE_NOT_ALLOWED,
    REPROCESSING_NOT_SAFE,
    REPROCESSING_APPROVER_MUST_DIFFER,
    REPROCESSING_PROPOSAL_EXPIRED,
    REPROCESSING_PROPOSAL_STALE,
    DEPENDENCY_UNAVAILABLE,
}

class DomainFailure(
    val code: FailureCode,
    override val message: String,
    val retryAfterSeconds: Long? = null,
) : RuntimeException(message)
