import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor, fn } from "storybook/test";
import { http, HttpResponse } from "msw";
import MockDate from "mockdate";
import type { components } from "../../api/schema";
import { SupportCompensationWorkspace } from "./SupportCompensationWorkspace";
const id = "75000000-0000-4000-8000-000000000001", orderId = "75000000-0000-4000-8000-000000000002", actionId = "75000000-0000-4000-8000-000000000003";
const supportCase = { caseId: id, state: "IN_PROGRESS", subjectLinks: [{ subjectType: "ORDER", display: { state: "AVAILABLE", label: "BF-7K9M-2P4R · 빈플로우 시청점" }, subjectId: orderId, relationship: "RELATED_ORDER" }] };
const verification = { sessionId: id, state: "VERIFIED", subjectType: "CUSTOMER", actionScope: "SUPPORT_ACTION", purpose: "CASE_RESOLUTION", expiresAt: "2026-09-11T09:15:00Z" };
const request: components["schemas"]["SupportCompensationResource"] = { compensationRequestId: id, supportCaseId: id, incidentId: id, orderId, storeId: id, benefitType: "POINT", amountKrw: 100, couponTemplateId: null, policyVersionId: id, band: "LOW", approvalRoute: "NONE", actionRequestId: null, state: "READY_FOR_EXECUTION", payloadDigest: "a".repeat(64), terminalBenefitId: null, benefitIssuedAt: null, notificationDeliveryId: null, notificationState: null, notificationFailureCode: null, version: 0, createdAt: "2026-09-11T09:01:00Z", updatedAt: "2026-09-11T09:01:00Z" };
const terms: components["schemas"]["SupportCompensationTermsResource"] = { responsibility: "PLATFORM", evidenceBasis: null, costEvidenceDigest: null, platformShareBps: 10000, storeShareBps: 0, evidenceDigest: "b".repeat(64), targetVersion: 4 };
const approval: components["schemas"]["SupportCompensationApprovalResource"] = { requestId: actionId, revisionNumber: 1, requestVersion: 2, state: "AWAITING_SUPPORT_MANAGER", caseVersion: 5, executorActorId: id };
const initial: components["schemas"]["SupportCompensationWorkflowResource"] = { request, terms, approval: null, currentTargetVersion: 4, verificationExpiresAt: verification.expiresAt, allowedActions: ["EXECUTE"], couponTemplate: null };
let current = initial;
const operatorDirectory = http.get("/api/v1/operations/operator-directory", () => HttpResponse.json({ items: [{ operatorId: orderId, loginName: "support.next", observedAt: "2026-09-11T00:00:00Z" }], nextCursor: null, missingProfileCount: 0 }));
const meta = { title: "Patterns/Support/Goodwill compensation", component: SupportCompensationWorkspace, tags: ["autodocs"], args: { supportCase, verification, initialCompensationId: id }, beforeEach() { current = structuredClone(initial); MockDate.set("2026-09-11T09:04:00Z"); return () => MockDate.reset(); }, parameters: { a11y: { test: "error" }, docs: { description: { component: "고객 불편 보상을 실제 정책으로 평가하고, 선택한 혜택·비용 책임에 대한 승인과 지급 및 알림 재시도를 처리합니다. 지급 완료와 알림 전달을 구분하고 응답 유실은 같은 명령으로 확인합니다." }, story: { inline: false, height: "1100px" } }, msw: { handlers: [operatorDirectory, http.get("/api/v1/support/compensations/:id/workflow", () => HttpResponse.json(current)), http.get("/api/v1/support/cases/:caseId/orders/:orderId", () => HttpResponse.json({ orderId, storeId: id, state: "PAID", version: 4 })), http.get("/api/v1/support/compensation-coupon-templates", () => HttpResponse.json({ items: [{ templateId: actionId, amountKrw: 1000, validityDays: 30, minimumEligibleSubtotalKrw: 3000 }], nextCursor: null }))] } } } satisfies Meta<typeof SupportCompensationWorkspace>;
export default meta; type Story = StoryObj<typeof meta>;
export const ExecutePoint: Story = { play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/compensations/:id/executions", async ({ request: req }) => { expect(await req.json()).toEqual({ expectedRequestVersion: 0, expectedTargetVersion: 4, expectedPayloadDigest: "a".repeat(64) }); current = { ...current, request: { ...current.request, state: "NOTIFICATION_ACCEPTED", terminalBenefitId: actionId, benefitIssuedAt: "2026-09-11T09:04:00Z", notificationState: "PENDING" }, allowedActions: [] }; return HttpResponse.json(current.request); })); await userEvent.click(await canvas.findByRole("checkbox", { name: "혜택과 비용 조건을 확인했습니다" })); await userEvent.click(canvas.getByRole("button", { name: "확인한 보상 지급" })); await expect(await canvas.findByText("혜택 지급 완료")).toBeVisible(); await expect(canvas.getByText(/알림 전달 상태/)).toBeVisible(); } };
export const CreateSharedPoint: Story = { args: { initialCompensationId: undefined }, play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/cases/:caseId/compensation-evaluations", async ({ request: req }) => { expect(await req.json()).toMatchObject({ responsibility: "SHARED", platformShareBps: 2550, storeShareBps: 7450, expectedTargetVersion: 4, benefitType: "POINT", amountKrw: 1000 }); return HttpResponse.json({ decision: "INVESTIGATION_REQUIRED", band: "EXCEPTIONAL", approvalRoute: "OPERATIONS", executable: true, reasonCodes: ["STORE_COST_RESPONSIBILITY"], targetVersion: 4, expiresAt: "2026-09-11T09:06:00Z" }); }), http.post("/api/v1/support/cases/:caseId/compensations", async ({ request: req }) => { const body = await req.json() as Record<string, unknown>; expect(body.evidenceDigest).toMatch(/^[a-f0-9]{64}$/); expect(body.costEvidenceDigest).toMatch(/^[a-f0-9]{64}$/); current = { ...initial, request: { ...request, amountKrw: 1000, band: "EXCEPTIONAL", approvalRoute: "OPERATIONS", actionRequestId: actionId, state: "AWAITING_APPROVAL" }, terms: { ...terms, responsibility: "SHARED", evidenceBasis: "STORE_CONSENT", platformShareBps: 2550, storeShareBps: 7450, evidenceDigest: String(body.evidenceDigest), costEvidenceDigest: String(body.costEvidenceDigest) }, approval: { ...approval, state: "AWAITING_OPERATIONS" }, allowedActions: [] }; return HttpResponse.json(current.request, { status: 201 }); })); await userEvent.type(await canvas.findByLabelText("사고 ID"), id); await userEvent.type(canvas.getByLabelText("보상 금액"), "1000"); await userEvent.selectOptions(canvas.getByLabelText("비용 책임"), "SHARED"); await userEvent.type(canvas.getByLabelText("플랫폼 부담 비율 (%)"), "25.5"); await userEvent.selectOptions(canvas.getByLabelText("비용 근거"), "STORE_CONSENT"); await userEvent.type(canvas.getByLabelText("비용 증빙 참조"), "점주 동의 기록 5"); await userEvent.type(canvas.getByLabelText("보상 증빙 참조"), "상담 기록 12"); await userEvent.click(canvas.getByRole("button", { name: "현재 보상 가능 여부 평가" })); await userEvent.click(await canvas.findByRole("button", { name: "평가한 보상 요청 등록" })); await expect(await canvas.findByText(`보상 ID ${id}`)).toBeVisible(); await expect(canvas.queryByText("혜택 지급 완료")).not.toBeInTheDocument(); await expect(canvas.getByText(/플랫폼 25.5%.*매장 74.5%/)).toBeVisible(); } };
export const CouponTemplate: Story = { args: { initialCompensationId: undefined }, play: async ({ canvas }) => { await userEvent.selectOptions(await canvas.findByLabelText("보상 혜택"), "COUPON"); await userEvent.click(await canvas.findByRole("button", { name: "₩1,000 쿠폰 선택" })); await expect(canvas.getByText(/최소 사용 금액.*3,000/)).toBeVisible(); await expect(canvas.getByText(/선택한 쿠폰.*1,000/)).toBeVisible(); await expect(canvas.queryByLabelText("보상 금액")).not.toBeInTheDocument(); } };
export const SeparateApproval: Story = { beforeEach() { current = { ...structuredClone(initial), request: { ...request, state: "AWAITING_APPROVAL", actionRequestId: actionId, band: "MEDIUM", approvalRoute: "SUPPORT_MANAGER" }, approval, allowedActions: ["DECIDE_SUPPORT_MANAGER"] }; }, play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/action-requests/:requestId/support-manager-decisions", async ({ request: req }) => { expect(await req.json()).toEqual({ revisionNumber: 1, expectedRequestVersion: 2, decision: "APPROVE", reason: "혜택과 비용 근거 검토 완료" }); current = { ...current, approval: { ...approval, state: "READY_FOR_EXECUTION", requestVersion: 3 }, allowedActions: [] }; return HttpResponse.json({}); })); await userEvent.click(await canvas.findByRole("checkbox", { name: "혜택과 비용 조건을 확인했습니다" })); await userEvent.type(canvas.getByLabelText("승인 결정 사유"), "혜택과 비용 근거 검토 완료"); await userEvent.click(canvas.getByRole("button", { name: "보상 승인 결정 기록" })); await expect(await canvas.findByText("보상 승인 결정을 기록했습니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "확인한 보상 지급" })).not.toBeInTheDocument(); } };
export const NotificationRetry: Story = { beforeEach() { current = { ...structuredClone(initial), request: { ...request, state: "NOTIFICATION_RETRY", terminalBenefitId: actionId, benefitIssuedAt: "2026-09-11T09:03:00Z", notificationFailureCode: "DEPENDENCY_UNAVAILABLE" }, allowedActions: ["RETRY_NOTIFICATION"] }; }, play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/compensations/:id/notification-retries", () => { current = { ...current, request: { ...current.request, state: "NOTIFICATION_ACCEPTED", notificationState: "PENDING" }, allowedActions: [] }; return HttpResponse.json(current.request); })); await expect(await canvas.findByText("혜택 지급 완료")).toBeVisible(); await userEvent.click(canvas.getByRole("button", { name: "보상 알림 다시 요청" })); await expect(await canvas.findByText("보상 알림을 다시 요청했습니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "확인한 보상 지급" })).not.toBeInTheDocument(); } };
export const UnknownRetry: Story = { play: async ({ canvas, msw }) => { const keys: string[] = []; msw.use(http.post("/api/v1/support/compensations/:id/executions", ({ request: req }) => { keys.push(req.headers.get("Idempotency-Key")!); if (keys.length === 1) return HttpResponse.error(); expect(keys[1]).toBe(keys[0]); return HttpResponse.json(request); })); await userEvent.click(await canvas.findByRole("checkbox", { name: "혜택과 비용 조건을 확인했습니다" })); await userEvent.click(canvas.getByRole("button", { name: "확인한 보상 지급" })); await userEvent.click(await canvas.findByRole("button", { name: "같은 보상 요청으로 결과 확인" })); await expect(await canvas.findByText("보상 지급 요청을 처리했습니다. 실제 지급과 알림 상태를 확인해 주세요.")).toBeVisible(); } };
export const StaleOrder: Story = { beforeEach() { current = { ...structuredClone(initial), currentTargetVersion: 5, allowedActions: [] }; }, play: async ({ canvas }) => { await expect(await canvas.findByText("보상 요청 이후 주문 정보가 변경되었습니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "확인한 보상 지급" })).not.toBeInTheDocument(); } };
export const PermissionLost: Story = { play: async ({ canvas, msw }) => { await canvas.findByRole("button", { name: "보상 상태 새로고침" }); msw.use(http.get("/api/v1/support/compensations/:id/workflow", () => HttpResponse.json({ code: "ACCESS_DENIED", correlationId: "COMPENSATION-REVOKED" }, { status: 403 }))); await userEvent.click(canvas.getByRole("button", { name: "보상 상태 새로고침" })); await expect(await canvas.findByText("문의 코드 COMPENSATION-REVOKED")).toBeVisible(); await waitFor(() => expect(canvas.queryByRole("button", { name: "확인한 보상 지급" })).not.toBeInTheDocument()); } };
export const Reassign: Story = { beforeEach() { current = { ...structuredClone(initial), request: { ...request, actionRequestId: actionId }, approval: { ...approval, state: "REASSIGNMENT_REQUIRED" }, allowedActions: ["REASSIGN"] }; }, play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/action-requests/:requestId/reassignments", async ({ request: req }) => { expect(await req.json()).toEqual({ revisionNumber: 1, expectedRequestVersion: 2, expectedCaseVersion: 5, assigneeId: orderId, reason: "새 담당자 인계" }); return HttpResponse.json({}); })); await userEvent.click(await canvas.findByRole("button", { name: "support.next 담당자 선택" })); await userEvent.type(canvas.getByLabelText("배정 사유"), "새 담당자 인계"); await userEvent.click(canvas.getByRole("button", { name: "보상과 상담 함께 재배정" })); await expect(await canvas.findByText("보상과 상담의 담당자를 변경했습니다")).toBeVisible(); } };

export const NotificationSkipped: Story = { beforeEach() { current = { ...structuredClone(initial), request: { ...request, state: "NOTIFICATION_SKIPPED", terminalBenefitId: actionId, benefitIssuedAt: "2026-09-11T09:03:00Z", notificationState: "NOTIFICATION_SKIPPED" }, allowedActions: [] }; }, play: async ({ canvas }) => { await expect(await canvas.findByText("혜택 지급 완료")).toBeVisible(); await expect(canvas.getAllByText("수신 설정에 따라 알림 생략")).toHaveLength(2); await expect(canvas.queryByRole("button", { name: "보상 알림 다시 요청" })).not.toBeInTheDocument(); } };
export const CouponReview: Story = { beforeEach() { current = { ...structuredClone(initial), request: { ...request, benefitType: "COUPON", amountKrw: 1000, couponTemplateId: actionId }, couponTemplate: { templateId: actionId, amountKrw: 1000, validityDays: 30, minimumEligibleSubtotalKrw: 3000 } }; }, play: async ({ canvas }) => { await expect(await canvas.findByText(/쿠폰 사용 기한 30일.*최소 사용 금액.*3,000/)).toBeVisible(); } };

export const OperationsReviewLink: Story = { beforeEach() { current = { ...current, approval: { ...approval, state: "AWAITING_OPERATIONS" }, allowedActions: [] }; }, play: async ({ canvas }) => { await expect(await canvas.findByRole("link", { name: "운영 조사 검토" })).toHaveAttribute("href", `/ops/support-investigations?requestId=${actionId}`); } };

export const SelectExistingRequest: Story = {
  args: { initialCompensationId: undefined, supportCase: undefined },
  play: async ({ canvas, msw }) => {
    const inspected = fn();
    msw.use(
      http.get("/api/v1/support/work-items", () => HttpResponse.json({ items: [{ requestId: id, caseId: id, kind: "COMPENSATION", caseCategory: "ACCOUNT_RECOVERY", caseOpenedAt: "2026-09-10T09:00:00Z", purpose: "CASE_RESOLUTION", state: "PENDING", createdAt: "2026-09-10T09:05:00Z", expiresAt: null }], nextCursor: null })),
      http.get("/api/v1/support/compensations/:id/workflow", async ({ params }) => { expect(params.id).toBe(id); inspected(); return HttpResponse.json(current); }),
    );
    await userEvent.click(canvas.getByRole("button", { name: "기존 보상 요청 찾기" }));
    await userEvent.click(await canvas.findByRole("button", { name: "이 요청 열기" }));
    await waitFor(() => expect(inspected).toHaveBeenCalled());
    await expect(canvas.getByRole("button", { name: "기존 보상 요청 찾기" })).toHaveAttribute("aria-expanded", "false");
  },
};

export const UndeterminedCost: Story = { args: { initialCompensationId: undefined }, play: async ({ canvas, msw }) => {
  msw.use(http.post("/api/v1/support/cases/:caseId/compensation-evaluations", async ({ request: req }) => {
    expect(await req.json()).toMatchObject({ responsibility: "UNDETERMINED", platformShareBps: 0, storeShareBps: 0 });
    return HttpResponse.json({ decision: "INVESTIGATION_REQUIRED", band: "EXCEPTIONAL", approvalRoute: "OPERATIONS", executable: false, reasonCodes: ["COST_RESPONSIBILITY_UNDETERMINED"], targetVersion: 4, expiresAt: "2026-09-11T09:06:00Z" });
  }));
  await userEvent.type(await canvas.findByLabelText("사고 ID"), id);
  await userEvent.type(canvas.getByLabelText("보상 금액"), "1000");
  await waitFor(() => expect(canvas.getByRole("button", { name: "현재 보상 가능 여부 평가" })).toBeEnabled());
  await userEvent.click(canvas.getByRole("button", { name: "현재 보상 가능 여부 평가" }));
  await expect(await canvas.findByText("비용 책임을 먼저 확정해 주세요")).toBeVisible();
  await expect(canvas.queryByRole("button", { name: "평가한 보상 요청 등록" })).not.toBeInTheDocument();
} };

export const UnavailableTargetsCannotSelect: Story = {
  args: { initialCompensationId: undefined, supportCase: { ...supportCase, subjectLinks: ["REQUIRES_PERMISSION", "MISSING_PROFILE"].map((state, index) => ({ ...supportCase.subjectLinks[0]!, linkId: `99020000-0000-4000-8000-00000000000${index + 1}`, subjectId: `99020000-0000-4000-8000-00000000000${index + 1}`, display: { state } })) } },
  play: async ({ canvas }) => {
    const select = await canvas.findByLabelText("보상 관련 주문");
    const unavailable = [...(select as HTMLSelectElement).options].filter(option => option.value);
    await expect(unavailable).toHaveLength(2);
    for (const option of unavailable) await expect(option).toBeDisabled();
    await expect(select).toHaveValue("");

  },
};
