import { useState } from "react";
import { Button } from "../../design-system";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent } from "storybook/test";
import { http, HttpResponse } from "msw";
import { SupportCaseManagementPage } from "./SupportCaseManagementPage";
const caseId = "a1000000-0000-4000-8000-000000000001";
const assigneeId = "a7000000-0000-4000-8000-000000000001";
const linkId = "a3000000-0000-4000-8000-000000000001";
const current = { caseId, state: "IN_PROGRESS", priority: "HIGH", assigneeId, assigneeDisplay: { state: "AVAILABLE", loginName: "support.current", observedAt: "2026-09-11T00:00:00Z" }, version: 4, openedAt: "2026-09-10T09:00:00Z", subjectLinks: [{ linkId, subjectType: "ORDER", subjectId: "a2000000-0000-4000-8000-000000000001", display: { state: "AVAILABLE", label: "BF-8K9M-2P4R · 빈플로우 시청점" }, relationship: "RELATED_ORDER", linkedAt: "2026-09-10T09:01:00Z" }] };
const read = http.get("/api/v1/support/cases/:caseId", () => HttpResponse.json(current));
const operatorDirectory = http.get("/api/v1/operations/operator-directory", () => HttpResponse.json({ items: [{ operatorId: assigneeId, loginName: "support.next", observedAt: "2026-09-11T00:00:00Z" }], nextCursor: null, missingProfileCount: 0 }));
const meta = { title: "Pages/Support/Case management", component: SupportCaseManagementPage, tags: ["autodocs"], parameters: { a11y: { test: "error" }, routing: { path: "/support/cases/:caseId", initialEntry: `/support/cases/${caseId}` }, msw: { handlers: [operatorDirectory, read] }, docs: { story: { inline: false, height: "1000px" } } } } satisfies Meta<typeof SupportCaseManagementPage>;
export default meta; type Story = StoryObj<typeof meta>;
export const Wait: Story = { play: async ({ canvas, msw }) => { await userEvent.selectOptions(await canvas.findByLabelText("변경할 상담 상태"), "WAITING"); await userEvent.type(canvas.getByLabelText("상태 변경 사유"), "고객 추가 자료 회신 대기"); msw.use(http.post("/api/v1/support/cases/:caseId/status-transitions", async ({ request }) => { expect(await request.json()).toEqual({ targetState: "WAITING", expectedVersion: 4, reason: "고객 추가 자료 회신 대기" }); msw.use(http.get("/api/v1/support/cases/:caseId", () => HttpResponse.json({ ...current, state: "WAITING", version: 5 }))); return HttpResponse.json({ currentState: "WAITING", caseVersion: 5 }); })); await userEvent.click(canvas.getByRole("button", { name: "상담 상태 변경" })); await expect(await canvas.findByText("상담 상태를 변경했습니다")).toBeVisible(); await expect(await canvas.findByRole("option", { name: "진행 중" })).toBeInTheDocument(); } };
export const Assign: Story = { play: async ({ canvas, msw }) => { await userEvent.click(await canvas.findByRole("tab", { name: "담당자 배정" })); await userEvent.click(await canvas.findByRole("button", { name: "support.next 담당자 선택" })); await userEvent.type(canvas.getByLabelText("배정 사유"), "환불 전담 상담사에게 이관"); msw.use(http.post("/api/v1/support/cases/:caseId/assignments", async ({ request }) => { expect(await request.json()).toEqual({ assigneeId, expectedVersion: 4, reason: "환불 전담 상담사에게 이관" }); return HttpResponse.json({ assigneeId, caseVersion: 5 }); })); await userEvent.click(canvas.getByRole("button", { name: "담당자 배정" })); await expect(await canvas.findByText("담당자를 배정했습니다")).toBeVisible(); } };
export const Interaction: Story = { play: async ({ canvas, msw }) => { await userEvent.click(await canvas.findByRole("tab", { name: "접촉 기록" })); await userEvent.selectOptions(canvas.getByLabelText("접촉 채널"), "EMAIL"); await userEvent.selectOptions(canvas.getByLabelText("접촉 방향"), "INBOUND"); await userEvent.type(canvas.getByLabelText("접촉 시각 (한국 시간)"), "2026-09-10T18:30"); await userEvent.type(canvas.getByLabelText("비식별 접촉 요약"), "고객이 주문 지연 확인을 요청함"); msw.use(http.post("/api/v1/support/cases/:caseId/interactions", async ({ request }) => { expect(await request.json()).toEqual({ channel: "EMAIL", direction: "INBOUND", occurredAt: "2026-09-10T09:30:00.000Z", redactedSummary: "고객이 주문 지연 확인을 요청함" }); return HttpResponse.json({ caseVersion: 5, summary: "고객이 주문 지연 확인을 요청함" }); })); await userEvent.click(canvas.getByRole("button", { name: "접촉 기록 추가" })); await expect(await canvas.findByText("접촉 기록을 추가했습니다")).toBeVisible(); } };
export const Note: Story = { play: async ({ canvas, msw }) => { await userEvent.click(await canvas.findByRole("tab", { name: "내부 노트" })); await userEvent.type(canvas.getByLabelText("내부 노트 내용"), "매장 답변 확인 후 환불 여부 안내 예정"); await userEvent.type(canvas.getByLabelText("노트 작성 사유"), "처리 방향 기록"); msw.use(http.post("/api/v1/support/cases/:caseId/notes", async ({ request }) => { expect(await request.json()).toEqual({ content: "매장 답변 확인 후 환불 여부 안내 예정", reason: "처리 방향 기록" }); return HttpResponse.json({ summary: "SUPPORT_NOTE_RECORDED", caseVersion: 5 }); })); await userEvent.click(canvas.getByRole("button", { name: "내부 노트 추가" })); await expect(await canvas.findByText("내부 노트를 추가했습니다")).toBeVisible(); await expect(await canvas.findByLabelText("내부 노트 내용")).toHaveValue(""); } };
export const Unlink: Story = { play: async ({ canvas, msw }) => { await userEvent.click(await canvas.findByRole("tab", { name: "대상 연결" })); await userEvent.type(canvas.getByLabelText("연결 해제 사유"), "다른 주문이 잘못 연결됨"); msw.use(http.delete("/api/v1/support/cases/:caseId/subject-links/:linkId", async ({ request, params }) => { expect(params.linkId).toBe(linkId); expect(await request.json()).toEqual({ expectedVersion: 4, reason: "다른 주문이 잘못 연결됨" }); msw.use(http.get("/api/v1/support/cases/:caseId", () => HttpResponse.json({ ...current, version: 5, subjectLinks: [] }))); return HttpResponse.json({ linkId, caseVersion: 5 }); })); await userEvent.click(canvas.getByRole("button", { name: "선택한 연결 해제" })); await expect(await canvas.findByText("대상 연결을 해제했습니다")).toBeVisible(); await expect(await canvas.findByText("연결된 대상이 없습니다")).toBeVisible(); } };
export const StaleVersion: Story = { parameters: { msw: { handlers: [operatorDirectory, read, http.post("/api/v1/support/cases/:caseId/status-transitions", () => HttpResponse.json({ code: "ORDER_STATE_CONFLICT", correlationId: "CASE-STALE" }, { status: 409 }))] } }, play: async ({ canvas }) => { await userEvent.selectOptions(await canvas.findByLabelText("변경할 상담 상태"), "WAITING"); await userEvent.type(canvas.getByLabelText("상태 변경 사유"), "추가 회신 대기"); await userEvent.click(canvas.getByRole("button", { name: "상담 상태 변경" })); await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByText("상담 상태를 변경했습니다")).not.toBeInTheDocument(); } };
export const Closed: Story = { parameters: { msw: { handlers: [operatorDirectory, http.get("/api/v1/support/cases/:caseId", () => HttpResponse.json({ ...current, state: "CLOSED", closedAt: "2026-09-10T10:00:00Z" }))] } }, play: async ({ canvas }) => { await expect(await canvas.findByText("종료된 상담은 변경할 수 없습니다")).toBeVisible(); await expect(canvas.queryByRole("tab", { name: "내부 노트" })).not.toBeInTheDocument(); } };
export const LostNoteResponse: Story = { play: async ({ canvas, msw }) => { await userEvent.click(await canvas.findByRole("tab", { name: "내부 노트" })); await userEvent.type(canvas.getByLabelText("내부 노트 내용"), "고객 회신 예정"); await userEvent.type(canvas.getByLabelText("노트 작성 사유"), "상담 기록"); let first: unknown; msw.use(http.post("/api/v1/support/cases/:caseId/notes", async ({ request }) => { first = { key: request.headers.get("Idempotency-Key"), body: await request.json() }; return HttpResponse.error(); })); await userEvent.click(canvas.getByRole("button", { name: "내부 노트 추가" })); await expect(await canvas.findByRole("button", { name: "같은 요청 결과 확인" })).toBeVisible(); msw.use(http.post("/api/v1/support/cases/:caseId/notes", async ({ request }) => { expect({ key: request.headers.get("Idempotency-Key"), body: await request.json() }).toEqual(first); return HttpResponse.json({ summary: "SUPPORT_NOTE_RECORDED", caseVersion: 5 }); })); await userEvent.click(canvas.getByRole("button", { name: "같은 요청 결과 확인" })); await expect(await canvas.findByText("내부 노트를 추가했습니다")).toBeVisible(); } };

export const LinkOrder: Story = { play: async ({ canvas, msw }) => { await userEvent.click(await canvas.findByRole("tab", { name: "대상 연결" })); await userEvent.selectOptions(canvas.getByLabelText("연결 대상 유형"), "ORDER"); msw.use(http.get("/api/v1/support/cases/:caseId/order-candidates/:reference", () => HttpResponse.json({ orderId: "a2000000-0000-4000-8000-000000000002", publicReference: "BF-7K9M-2P4R", storeName: "빈플로우 시청점", state: "ACCEPTED" }))); await userEvent.type(canvas.getByLabelText("공개 주문번호"), "BF-7K9M-2P4R"); await userEvent.click(canvas.getByRole("button", { name: "대상 정확 검색" })); await userEvent.click(await canvas.findByRole("button", { name: "BF-7K9M-2P4R · 빈플로우 시청점 대상 선택" })); await userEvent.selectOptions(canvas.getByLabelText("상담과의 관계"), "RELATED_ORDER"); await userEvent.type(canvas.getByLabelText("연결 사유"), "문의 대상 주문 확인"); msw.use(http.post("/api/v1/support/cases/:caseId/subject-links", async ({ request }) => { expect(await request.json()).toEqual({ subjectType: "ORDER", subjectId: "a2000000-0000-4000-8000-000000000002", relationship: "RELATED_ORDER", reason: "문의 대상 주문 확인" }); return HttpResponse.json({ linkId: "linked-order", caseVersion: 5 }); })); await userEvent.click(canvas.getByRole("button", { name: "상담 대상 연결" })); await expect(await canvas.findByText("대상을 연결했습니다")).toBeVisible(); } };
export const FailedRefresh: Story = { play: async ({ canvas, msw }) => { await userEvent.selectOptions(await canvas.findByLabelText("변경할 상담 상태"), "WAITING"); await userEvent.type(canvas.getByLabelText("상태 변경 사유"), "자료 회신 대기"); msw.use(http.post("/api/v1/support/cases/:caseId/status-transitions", () => { msw.use(http.get("/api/v1/support/cases/:caseId", () => HttpResponse.json({ code: "DEPENDENCY_UNAVAILABLE", correlationId: "CASE-READ-UNAVAILABLE" }, { status: 503 }))); return HttpResponse.json({ currentState: "WAITING", caseVersion: 5 }); })); await userEvent.click(canvas.getByRole("button", { name: "상담 상태 변경" })); await expect(await canvas.findByText("문의 코드 CASE-READ-UNAVAILABLE")).toBeVisible(); await expect(canvas.queryByRole("tab", { name: "상태 변경" })).not.toBeInTheDocument(); } };
export const FutureInteraction: Story = { play: async ({ canvas }) => { await userEvent.click(await canvas.findByRole("tab", { name: "접촉 기록" })); await userEvent.selectOptions(canvas.getByLabelText("접촉 채널"), "PHONE"); await userEvent.selectOptions(canvas.getByLabelText("접촉 방향"), "OUTBOUND"); await userEvent.type(canvas.getByLabelText("접촉 시각 (한국 시간)"), "2099-01-01T12:00"); await userEvent.type(canvas.getByLabelText("비식별 접촉 요약"), "고객 문의 확인"); await userEvent.click(canvas.getByRole("button", { name: "접촉 기록 추가" })); await expect(await canvas.findByText("접촉 시각은 현재까지의 유효한 한국 시간으로 입력해 주세요.")).toBeVisible(); } };

export const CustomerConversation: Story = { parameters: { msw: { handlers: [operatorDirectory, http.get("/api/v1/support/cases/:caseId", () => HttpResponse.json({ ...current, customerInquiryId: "b1000000-0000-4000-8000-000000000001" }))] } }, play: async ({ canvas }) => { await expect(await canvas.findByRole("link", { name: "고객 공개 문의와 답변" })).toHaveAttribute("href", "/support/inquiries/b1000000-0000-4000-8000-000000000001"); } };
export const RemovedSelectionDoesNotRetarget: Story = { play: async ({ canvas, msw }) => {
  const otherLink = { ...current.subjectLinks[0], linkId: "a3000000-0000-4000-8000-000000000002", subjectId: "a2000000-0000-4000-8000-000000000002" };
  msw.use(http.get("/api/v1/support/cases/:caseId", () => HttpResponse.json({ ...current, subjectLinks: [...current.subjectLinks, otherLink] })));
  await userEvent.click(await canvas.findByRole("button", { name: "상담 상태 새로고침" }));
  await userEvent.click(await canvas.findByRole("tab", { name: "대상 연결" }));
  await userEvent.selectOptions(canvas.getByLabelText("해제할 대상 연결"), otherLink.linkId);
  await userEvent.type(canvas.getByLabelText("연결 해제 사유"), "두 번째 주문 연결만 해제");
  msw.use(http.get("/api/v1/support/cases/:caseId", () => HttpResponse.json({ ...current, version: 5 })));
  await userEvent.click(canvas.getByRole("button", { name: "상담 상태 새로고침" }));
  await expect(await canvas.findByLabelText("해제할 대상 연결")).toHaveValue("");
  await expect(canvas.getByRole("button", { name: "선택한 연결 해제" })).toBeDisabled();
} };

function ReopenCaseManagement() {
  const [revision, setRevision] = useState(0);
  return <><Button onClick={() => setRevision(value => value + 1)}>화면 다시 열기</Button><SupportCaseManagementPage key={revision} /></>;
}
export const LostNoteSurvivesReentry: Story = { render: () => <ReopenCaseManagement />, play: async ({ canvas, msw }) => {
  let first: { key: string | null; body: unknown } | null = null;
  msw.use(http.post("/api/v1/support/cases/:caseId/notes", async ({ request }) => {
    const sent = { key: request.headers.get("Idempotency-Key"), body: await request.json() };
    if (!first) { first = sent; return HttpResponse.error(); }
    expect(sent).toEqual(first); return HttpResponse.json({ summary: "SUPPORT_NOTE_RECORDED", caseVersion: 5 });
  }));
  async function writeNote() {
    await userEvent.click(await canvas.findByRole("tab", { name: "내부 노트" }));
    await userEvent.type(canvas.getByLabelText("내부 노트 내용"), "고객 회신 예정");
    await userEvent.type(canvas.getByLabelText("노트 작성 사유"), "상담 기록");
    await userEvent.click(canvas.getByRole("button", { name: "내부 노트 추가" }));
  }
  await writeNote();
  await expect(await canvas.findByRole("button", { name: "같은 요청 결과 확인" })).toBeVisible();
  expect(JSON.stringify(Object.entries(sessionStorage))).not.toContain("고객 회신 예정");
  await userEvent.click(canvas.getByRole("button", { name: "화면 다시 열기" }));
  await writeNote();
  await expect(await canvas.findByText("내부 노트를 추가했습니다")).toBeVisible();
} };

export const UnavailableTargetsCannotUnlink: Story = {
  parameters: { msw: { handlers: [operatorDirectory, http.get("/api/v1/support/cases/:caseId", () => HttpResponse.json({ ...current, subjectLinks: ["REQUIRES_PERMISSION", "MISSING_PROFILE"].map((state, index) => ({ ...current.subjectLinks[0], linkId: `99020000-0000-4000-8000-00000000000${index + 1}`, subjectId: `99020000-0000-4000-8000-00000000000${index + 1}`, display: { state } })) }))] } },
  play: async ({ canvas }) => { await userEvent.click(await canvas.findByRole("tab", { name: "대상 연결" })); const select = canvas.getByLabelText("해제할 대상 연결") as HTMLSelectElement; for (const option of [...select.options].filter(option => option.value)) await expect(option).toBeDisabled(); await userEvent.type(canvas.getByLabelText("연결 해제 사유"), "대상 확인 전"); await expect(select).toHaveValue(""); await expect(canvas.getByRole("button", { name: "선택한 연결 해제" })).toBeDisabled(); },
};
