import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor } from "storybook/test";
import { http, HttpResponse } from "msw";
import MockDate from "mockdate";
import { SupportOrderActionWorkspace } from "./SupportOrderActionWorkspace";
import { orderChangeDigest } from "../../lib/supportOrderPayload";

const caseId = "71000000-0000-4000-8000-000000000001", orderId = "71000000-0000-4000-8000-000000000002", storeId = "71000000-0000-4000-8000-000000000003", requestId = "71000000-0000-4000-8000-000000000004", sessionId = "71000000-0000-4000-8000-000000000005";
const order = { orderId, storeId, state: "PAID", version: 2 };
const session = { sessionId, state: "VERIFIED", actionScope: "SUPPORT_ACTION", purpose: "CASE_RESOLUTION", expiresAt: "2026-09-11T09:15:00Z" };
const supportCase = { caseId, state: "IN_PROGRESS", subjectLinks: [{ subjectType: "ORDER", subjectId: orderId, relationship: "RELATED_ORDER" }] };
const request = { requestId, caseId, action: "ORDER_CANCELLATION", targetId: orderId, requesterActorId: sessionId, executorActorId: sessionId, revisionNumber: 1, state: "READY_FOR_EXECUTION", approvalRoute: "NONE", actionPayloadDigest: "", verificationSessionId: sessionId, policyVersion: "support-action-policy/2026-08-12/v1", targetVersion: 2, amountKrw: null, evidenceDigest: "a".repeat(64), expiresAt: session.expiresAt, requestVersion: 0, approvalSteps: [], terminalExecutionId: null, terminalResolutionId: null };
const workflow = async (state = "READY_FOR_EXECUTION", allowedActions = ["EXECUTE"]) => ({ request: { ...request, state, actionPayloadDigest: await orderChangeDigest("ORDER_CANCELLATION", orderId, "CHANGED_MIND", "") }, order, caseVersion: 4, allowedActions });
const meta = { title: "Patterns/Support/Order actions", component: SupportOrderActionWorkspace, tags: ["autodocs"], args: { supportCase, verification: session, initialRequestId: requestId }, beforeEach() { MockDate.set("2026-09-11T09:04:00Z"); return () => MockDate.reset(); }, parameters: { a11y: { test: "error" }, routing: { path: "/support/follow-up", initialEntry: `/support/follow-up?caseId=${caseId}` }, docs: { story: { inline: false, height: "1050px" } }, msw: { handlers: [http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json(await workflow())), http.get("/api/v1/support/cases/:caseId/orders/:orderId", () => HttpResponse.json(order))] } } } satisfies Meta<typeof SupportOrderActionWorkspace>;
export default meta; type Story = StoryObj<typeof meta>;
export const ExecuteCancellation: Story = { play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/action-requests/:requestId/executions", async ({ request: req }) => { expect(await req.json()).toEqual({ action: "ORDER_CANCELLATION", reasonCode: "CHANGED_MIND", revisionNumber: 1, expectedRequestVersion: 0, expectedTargetVersion: 2 }); msw.use(http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json(await workflow("EXECUTED", [])))); return HttpResponse.json({ executionId: requestId, outcome: "EXECUTED", currentTargetState: "CANCELLED", paymentRecoveryState: "REQUESTED" }); })); await waitFor(() => expect(canvas.getByRole("button", { name: "확인한 주문 변경 실행" })).toBeEnabled()); await userEvent.click(canvas.getByRole("button", { name: "확인한 주문 변경 실행" })); await expect(await canvas.findByText("주문 변경을 처리했습니다")).toBeVisible(); await expect(canvas.getByText("환불 요청 접수")).toBeVisible(); await waitFor(() => expect(canvas.queryByRole("button", { name: "확인한 주문 변경 실행" })).not.toBeInTheDocument()); } };
export const CreateRequest: Story = { args: { initialRequestId: undefined }, play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/cases/:caseId/action-evaluations", () => HttpResponse.json({ action: "ORDER_CANCELLATION", orderId, decision: "ALLOWED", reasonCodes: ["POLICY_ALLOWED"], requiredVerificationLevel: "BASIC", approvalRequirements: [], targetVersion: 2, expiresAt: "2026-09-11T09:06:00Z" })), http.post("/api/v1/support/cases/:caseId/action-requests", async ({ request: req }) => { const body = await req.json() as Record<string, unknown>; expect(body.expectedTargetVersion).toBe(2); expect(body.verificationSessionId).toBe(sessionId); expect(body.actionPayloadDigest).toBe(await orderChangeDigest("ORDER_CANCELLATION", orderId, "CHANGED_MIND", "")); expect(body.evidenceDigest).toMatch(/^[a-f0-9]{64}$/); expect(body).not.toHaveProperty("evidence"); return HttpResponse.json(request, { status: 201 }); })); await userEvent.click(await canvas.findByRole("button", { name: "현재 주문 변경 가능 여부 확인" })); await userEvent.type(await canvas.findByLabelText("요청 사유"), "고객이 취소를 요청했습니다"); await userEvent.type(canvas.getByLabelText("증빙 참조"), "상담 기록 번호 42"); await userEvent.click(await canvas.findByRole("button", { name: "주문 변경 요청 등록" })); await expect(await canvas.findByText(`요청 ID ${requestId}`)).toBeVisible(); } };
export const DeniedEvaluation: Story = { args: { initialRequestId: undefined }, play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/cases/:caseId/action-evaluations", () => HttpResponse.json({ decision: "DENIED", reasonCodes: ["STALE_TARGET_VERSION"], targetVersion: 3, requiredVerificationLevel: "BASIC", expiresAt: "2026-09-11T09:06:00Z" }))); await userEvent.click(await canvas.findByRole("button", { name: "현재 주문 변경 가능 여부 확인" })); await expect(await canvas.findByText(/주문 정보가 변경되었습니다/)).toBeVisible(); await expect(canvas.queryByRole("button", { name: "주문 변경 요청 등록" })).not.toBeInTheDocument(); } };
export const SeparateApproval: Story = { parameters: { msw: { handlers: [http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json(await workflow("AWAITING_SUPPORT_MANAGER", ["DECIDE_SUPPORT_MANAGER"]))) ] } }, play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/action-requests/:requestId/support-manager-decisions", async ({ request: req }) => { expect(await req.json()).toEqual({ revisionNumber: 1, expectedRequestVersion: 0, decision: "APPROVE", reason: "요청 내용과 증빙을 확인했습니다" }); msw.use(http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json(await workflow("READY_FOR_EXECUTION", [])))); return HttpResponse.json(request); })); await userEvent.type(await canvas.findByLabelText("결정 사유"), "요청 내용과 증빙을 확인했습니다"); await userEvent.click(canvas.getByRole("button", { name: "승인 결정 기록" })); await expect(await canvas.findByText("승인 결정을 기록했습니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "확인한 주문 변경 실행" })).not.toBeInTheDocument(); } };
export const ChangedPayloadBlocked: Story = { play: async ({ canvas }) => { await userEvent.selectOptions(await canvas.findByLabelText("취소 사유 확인"), "OTHER"); await expect(await canvas.findByText("선택한 내용이 현재 승인안과 다릅니다")).toBeVisible(); await expect(canvas.getByRole("button", { name: "확인한 주문 변경 실행" })).toBeDisabled(); } };
export const Expired: Story = { parameters: { msw: { handlers: [http.get("/api/v1/support/action-requests/:requestId/workflow", async () => { const value = await workflow(); return HttpResponse.json({ ...value, request: { ...value.request, expiresAt: "2026-09-11T09:03:00Z" } }); })] } }, play: async ({ canvas }) => { await expect(await canvas.findByText("승인안의 유효 시간이 지났습니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "확인한 주문 변경 실행" })).not.toBeInTheDocument(); } };
export const FailedRefresh: Story = { play: async ({ canvas, msw }) => { await canvas.findByRole("button", { name: "요청 상태 새로고침" }); msw.use(http.get("/api/v1/support/action-requests/:requestId/workflow", () => HttpResponse.json({ code: "ACCESS_DENIED", correlationId: "ACTION-REVOKED" }, { status: 403 }))); await userEvent.click(canvas.getByRole("button", { name: "요청 상태 새로고침" })); await expect(await canvas.findByText("문의 코드 ACTION-REVOKED")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "확인한 주문 변경 실행" })).not.toBeInTheDocument(); } };
export const UnknownRetry: Story = { play: async ({ canvas, msw }) => { const keys: string[] = []; msw.use(http.post("/api/v1/support/action-requests/:requestId/executions", ({ request: req }) => { keys.push(req.headers.get("Idempotency-Key")!); if (keys.length === 1) return HttpResponse.error(); expect(keys[1]).toBe(keys[0]); msw.use(http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json(await workflow("EXECUTED", [])))); return HttpResponse.json({ outcome: "EXECUTED", currentTargetState: "CANCELLED", paymentRecoveryState: "REQUESTED" }); })); await waitFor(() => expect(canvas.getByRole("button", { name: "확인한 주문 변경 실행" })).toBeEnabled()); await userEvent.click(canvas.getByRole("button", { name: "확인한 주문 변경 실행" })); await userEvent.click(await canvas.findByRole("button", { name: "같은 요청으로 결과 확인" })); await expect(await canvas.findByText("주문 변경을 처리했습니다")).toBeVisible(); } };

export const ReviseRequest: Story = { parameters: { msw: { handlers: [http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json(await workflow("REVISION_REQUIRED", ["REVISE"])))] } }, play: async ({ canvas, msw }) => {
  msw.use(http.get("/api/v1/support/cases/:caseId/orders/:orderId", () => HttpResponse.json(order)), http.post("/api/v1/support/cases/:caseId/action-evaluations", () => HttpResponse.json({ decision: "ALLOWED", reasonCodes: ["POLICY_ALLOWED"], requiredVerificationLevel: "BASIC", targetVersion: 2, expiresAt: "2026-09-11T09:06:00Z" })), http.post("/api/v1/support/action-requests/:requestId/revisions", async ({ request: req }) => { const body = await req.json() as Record<string, unknown>; expect(body.expectedRevisionNumber).toBe(1); expect(body.expectedRequestVersion).toBe(0); expect(body.expectedTargetVersion).toBe(2); expect(body.actionPayloadDigest).toBe(await orderChangeDigest("ORDER_CANCELLATION", orderId, "OTHER", "")); msw.use(http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json({ ...(await workflow("AWAITING_SUPPORT_MANAGER", [])), request: { ...request, state: "AWAITING_SUPPORT_MANAGER", revisionNumber: 2, requestVersion: 1 } }))); return HttpResponse.json({ ...request, revisionNumber: 2 }); }));
  await userEvent.click(await canvas.findByRole("button", { name: "승인안 수정" })); await userEvent.selectOptions(await canvas.findByLabelText("취소 사유 확인"), "OTHER"); await userEvent.click(canvas.getByRole("button", { name: "현재 주문 변경 가능 여부 확인" })); await userEvent.type(await canvas.findByLabelText("요청 사유"), "취소 사유를 다시 확인했습니다"); await userEvent.type(canvas.getByLabelText("증빙 참조"), "상담 기록 43"); await userEvent.click(canvas.getByRole("button", { name: "새 승인안 제출" })); await expect(await canvas.findByText("새 승인안을 제출했습니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "확인한 주문 변경 실행" })).not.toBeInTheDocument();
} };
export const ReassignExecutor: Story = { parameters: { msw: { handlers: [http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json(await workflow("REASSIGNMENT_REQUIRED", ["REASSIGN"])))] } }, play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/action-requests/:requestId/reassignments", async ({ request: req }) => { expect(await req.json()).toEqual({ revisionNumber: 1, expectedRequestVersion: 0, expectedCaseVersion: 4, assigneeId: storeId, reason: "담당자 변경" }); msw.use(http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json(await workflow("READY_FOR_EXECUTION", [])))); return HttpResponse.json({ ...request, executorActorId: storeId }); })); await userEvent.type(await canvas.findByLabelText("새 실행 담당자 ID"), storeId); await userEvent.type(canvas.getByLabelText("배정 사유"), "담당자 변경"); await userEvent.click(canvas.getByRole("button", { name: "상담과 요청 함께 재배정" })); await expect(await canvas.findByText("상담과 요청의 담당자를 변경했습니다")).toBeVisible(); } };
export const PreparingRequiresResolution: Story = { play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/action-requests/:requestId/executions", () => { msw.use(http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json(await workflow("RESOLUTION_REQUIRED", [])))); return HttpResponse.json({ outcome: "RESOLUTION_REQUIRED", currentTargetState: "PREPARING", paymentRecoveryState: null }); })); await waitFor(() => expect(canvas.getByRole("button", { name: "확인한 주문 변경 실행" })).toBeEnabled()); await userEvent.click(canvas.getByRole("button", { name: "확인한 주문 변경 실행" })); await expect(await canvas.findByText("수락 후 해결 업무로 전환해야 합니다")).toBeVisible(); await expect(canvas.queryByText("주문 변경을 처리했습니다")).not.toBeInTheDocument(); } };
export const PickupReschedule: Story = { parameters: { msw: { handlers: [http.get("/api/v1/support/action-requests/:requestId/workflow", async () => HttpResponse.json({ ...(await workflow()), request: { ...request, action: "PICKUP_RESCHEDULE", actionPayloadDigest: await orderChangeDigest("PICKUP_RESCHEDULE", orderId, "CHANGED_MIND", storeId) } })), http.get("/api/v1/support/action-requests/:requestId/pickup-slots", () => HttpResponse.json({ items: [{ pickupSlotId: storeId, startsAt: "2026-09-11T09:20:00Z", endsAt: "2026-09-11T09:30:00Z", remainingCapacity: 2 }] }))] } }, play: async ({ canvas, msw }) => { msw.use(http.post("/api/v1/support/action-requests/:requestId/executions", async ({ request: req }) => { expect(await req.json()).toEqual({ action: "PICKUP_RESCHEDULE", newPickupSlotId: storeId, revisionNumber: 1, expectedRequestVersion: 0, expectedTargetVersion: 2 }); return HttpResponse.json({ outcome: "EXECUTED", currentTargetState: "PAID", paymentRecoveryState: null }); })); await userEvent.selectOptions(await canvas.findByLabelText("변경할 픽업 시간"), storeId); await waitFor(() => expect(canvas.getByRole("button", { name: "확인한 주문 변경 실행" })).toBeEnabled()); await userEvent.click(canvas.getByRole("button", { name: "확인한 주문 변경 실행" })); await expect(await canvas.findByText("주문 변경을 처리했습니다")).toBeVisible(); } };

export const CreatePickupRequest: Story = { args: { initialRequestId: undefined }, play: async ({ canvas, msw }) => {
  msw.use(http.get("/api/v1/support/cases/:caseId/orders/:orderId/pickup-slots", () => HttpResponse.json({ items: [{ pickupSlotId: storeId, startsAt: "2026-09-11T09:20:00Z", endsAt: "2026-09-11T09:30:00Z", remainingCapacity: 2 }] })), http.get("/api/v1/stores/:storeId/pickup-slots", () => { throw new Error("Customer session must not be used"); }));
  await userEvent.selectOptions(await canvas.findByLabelText("주문 변경 업무"), "PICKUP_RESCHEDULE");
  await userEvent.selectOptions(await canvas.findByLabelText("변경할 픽업 시간"), storeId);
  await expect(canvas.getByLabelText("변경할 픽업 시간")).toHaveValue(storeId);
} };
