import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, fn, userEvent, waitFor } from "storybook/test";
import { http, HttpResponse } from "msw";
import MockDate from "mockdate";
import { SupportVerificationPanel } from "./SupportVerificationPanel";
import type { components } from "../../api/schema";
const caseId = "a1000000-0000-4000-8000-000000000001";
const linkId = "a3000000-0000-4000-8000-000000000001";
const sessionId = "a4000000-0000-4000-8000-000000000001";
const secondId = "a4000000-0000-4000-8000-000000000002";
const future = "2026-09-10T09:15:00Z";
const session: components["schemas"]["VerificationSessionResource"] = { sessionId, caseId, subjectLinkId: linkId, subjectType: "CUSTOMER", subjectId: "a2000000-0000-4000-8000-000000000001", purpose: "CONTACT_CONFIRMATION", actionScope: "PERSONAL_DATA_REVEAL", requestedLevel: "ENHANCED", achievedLevel: "UNVERIFIED", state: "PENDING", invalidAttempts: 0, startedAt: "2026-09-10T09:00:00Z", expiresAt: future, version: 0, challenges: [] };
const meta = { title: "Patterns/Support/Verification", component: SupportVerificationPanel, tags: ["autodocs"], beforeEach: () => { MockDate.set("2026-09-10T09:04:00Z"); return () => MockDate.reset(); }, args: { caseId, links: [{ linkId, subjectType: "CUSTOMER", subjectId: session.subjectId, relationship: "REQUESTER", linkedAt: "2026-09-10T09:00:00Z" }], disabled: false, onChange: fn() }, parameters: { a11y: { test: "error" }, docs: { story: { inline: false, height: "1100px" } } } } satisfies Meta<typeof SupportVerificationPanel>;
export default meta; type Story = StoryObj<typeof meta>;
async function start(canvas: Parameters<NonNullable<Story["play"]>>[0]["canvas"]) { await userEvent.selectOptions(canvas.getByLabelText("본인확인 대상"), linkId); await userEvent.click(canvas.getByRole("button", { name: "본인확인 시작" })); await canvas.findByText(`본인확인 ID ${sessionId}`); }
export const Enhanced: Story = { play: async ({ canvas, msw, args }) => { let current = structuredClone(session); msw.use(http.post("/api/v1/support/cases/:caseId/verification-sessions", async ({ request }) => { expect(await request.json()).toEqual({ subjectLinkId: linkId, requestedLevel: "ENHANCED", purpose: "CONTACT_CONFIRMATION", actionScope: "PERSONAL_DATA_REVEAL" }); return HttpResponse.json(current, { status: 201 }); }), http.get("/api/v1/support/verification-sessions/:sessionId", () => HttpResponse.json(current)), http.post("/api/v1/support/verification-sessions/:sessionId/challenges", async ({ request }) => { const body = await request.json() as { channel: "REGISTERED_PHONE" | "REGISTERED_EMAIL" }; const challenge = { challengeId: body.channel === "REGISTERED_PHONE" ? sessionId : secondId, sessionId, channel: body.channel, state: "ISSUED" as const, requestedAt: session.startedAt, expiresAt: future }; current = { ...current, challenges: [...current.challenges, challenge] }; return HttpResponse.json(challenge, { status: 201 }); }), http.post("/api/v1/support/verification-challenges/:challengeId/verifications", async ({ params, request }) => { expect(await request.json()).toEqual({ proof: "123456" }); current = { ...current, challenges: current.challenges.map(c => c.challengeId === params.challengeId ? { ...c, state: "VERIFIED" as const } : c) }; if (current.challenges.filter(c => c.state === "VERIFIED").length === 2) current = { ...current, state: "VERIFIED", achievedLevel: "ENHANCED" }; return HttpResponse.json({ challenge: current.challenges.find(c => c.challengeId === params.challengeId), sessionState: current.state, achievedLevel: current.achievedLevel, invalidAttempts: 0, lockedUntil: null }); })); await start(canvas); for (const channel of ["REGISTERED_PHONE", "REGISTERED_EMAIL"]) { await userEvent.selectOptions(await canvas.findByLabelText("인증 수단"), channel); await userEvent.click(canvas.getByRole("button", { name: "인증 요청 발급" })); await userEvent.type(await canvas.findByLabelText("일회성 인증 코드"), "123456"); await userEvent.click(canvas.getByRole("button", { name: "인증 코드 확인" })); await waitFor(() => expect(canvas.queryByLabelText("일회성 인증 코드")).not.toBeInTheDocument()); } await expect(await canvas.findByText("본인확인이 완료되었습니다")).toBeVisible(); await waitFor(() => expect(args.onChange).toHaveBeenLastCalledWith(expect.objectContaining({ state: "VERIFIED", achievedLevel: "ENHANCED", challenges: expect.arrayContaining([expect.objectContaining({ channel: "REGISTERED_PHONE" }), expect.objectContaining({ channel: "REGISTERED_EMAIL" })]) }))); } };
export const ActionScope: Story = { play: async ({ canvas, msw }) => { const current = { ...session, purpose: "CASE_RESOLUTION", actionScope: "SUPPORT_ACTION", requestedLevel: "BASIC" }; msw.use(http.post("/api/v1/support/cases/:caseId/verification-sessions", async ({ request }) => { expect(await request.json()).toEqual({ subjectLinkId: linkId, purpose: "CASE_RESOLUTION", actionScope: "SUPPORT_ACTION", requestedLevel: "BASIC" }); return HttpResponse.json(current, { status: 201 }); }), http.get("/api/v1/support/verification-sessions/:sessionId", () => HttpResponse.json(current))); await userEvent.selectOptions(canvas.getByLabelText("인증 사용 업무"), "SUPPORT_ACTION"); await userEvent.selectOptions(canvas.getByLabelText("요청 인증 수준"), "BASIC"); await expect(canvas.getByLabelText("본인확인 목적")).toBeDisabled(); await start(canvas); await expect(canvas.getByText("상담 조치 · 상담 해결")).toBeVisible(); } };
export const Revoke: Story = { play: async ({ canvas, msw }) => { let current = { ...session, state: "VERIFIED", achievedLevel: "ENHANCED" }; msw.use(http.get("/api/v1/support/verification-sessions/:sessionId", () => HttpResponse.json(current)), http.post("/api/v1/support/verification-sessions/:sessionId/revocations", () => { current = { ...current, state: "REVOKED" }; return HttpResponse.json(current); })); await userEvent.type(canvas.getByLabelText("기존 본인확인 ID"), sessionId); await userEvent.click(canvas.getByRole("button", { name: "본인확인 현재 상태 조회" })); await userEvent.click(await canvas.findByRole("button", { name: "본인확인 철회" })); await expect(await canvas.findByText("본인확인이 철회되었습니다")).toBeVisible(); } };
export const UnknownChallenge: Story = { play: async ({ canvas, msw }) => { const current = { ...session, challenges: [{ challengeId: secondId, sessionId, channel: "REGISTERED_PHONE", state: "VERIFICATION_UNKNOWN", requestedAt: session.startedAt, expiresAt: future }] }; msw.use(http.get("/api/v1/support/verification-sessions/:sessionId", () => HttpResponse.json(current))); await userEvent.type(canvas.getByLabelText("기존 본인확인 ID"), sessionId); await userEvent.click(canvas.getByRole("button", { name: "본인확인 현재 상태 조회" })); await expect(await canvas.findByText("인증 결과를 확인하고 있습니다")).toBeVisible(); await expect(canvas.queryByLabelText("일회성 인증 코드")).not.toBeInTheDocument(); } };
export const Locked: Story = { play: async ({ canvas, msw }) => { msw.use(http.get("/api/v1/support/verification-sessions/:sessionId", () => HttpResponse.json({ ...session, state: "LOCKED", invalidAttempts: 5 }))); await userEvent.type(canvas.getByLabelText("기존 본인확인 ID"), sessionId); await userEvent.click(canvas.getByRole("button", { name: "본인확인 현재 상태 조회" })); await expect(await canvas.findByText("본인확인이 잠겼습니다")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "인증 요청 발급" })).not.toBeInTheDocument(); } };
export const WrongCase: Story = { play: async ({ canvas, msw }) => { msw.use(http.get("/api/v1/support/verification-sessions/:sessionId", () => HttpResponse.json({ ...session, caseId: secondId }))); await userEvent.type(canvas.getByLabelText("기존 본인확인 ID"), sessionId); await userEvent.click(canvas.getByRole("button", { name: "본인확인 현재 상태 조회" })); await expect(await canvas.findByRole("alert")).toBeVisible(); await expect(canvas.queryByRole("button", { name: "인증 요청 발급" })).not.toBeInTheDocument(); } };
export const ClosedCase: Story = { args: { disabled: true }, play: async ({ canvas }) => { await expect(canvas.getByText(/종료된 상담 건에서는/)).toBeVisible(); await expect(canvas.queryByRole("button", { name: "본인확인 시작" })).not.toBeInTheDocument(); } };

export const InitialActionScope: Story = { args: { initialActionScope: "SUPPORT_ACTION" }, play: async ({ canvas }) => { await expect(canvas.getByLabelText("인증 사용 업무")).toHaveValue("SUPPORT_ACTION"); await expect(canvas.getByLabelText("본인확인 목적")).toBeDisabled(); } };

export const ExpiredChallengeAllowsReissue: Story = { play: async ({ canvas, msw }) => {
  const edge = Date.now() + 1000;
  const current = { ...session, challenges: [{ challengeId: secondId, sessionId, channel: "REGISTERED_PHONE", state: "ISSUED", requestedAt: session.startedAt, expiresAt: new Date(edge).toISOString() }] };
  msw.use(http.get("/api/v1/support/verification-sessions/:sessionId", () => HttpResponse.json(current)));
  await userEvent.type(canvas.getByLabelText("기존 본인확인 ID"), sessionId);
  await userEvent.click(canvas.getByRole("button", { name: "본인확인 현재 상태 조회" }));
  await expect(await canvas.findByLabelText("일회성 인증 코드")).toBeVisible();
  MockDate.set(edge);
  await userEvent.click(canvas.getByRole("button", { name: "본인확인 새로고침" }));
  await waitFor(() => expect(canvas.queryByLabelText("일회성 인증 코드")).not.toBeInTheDocument(), { timeout: 3000 });
  await userEvent.selectOptions(canvas.getByLabelText("인증 수단"), "REGISTERED_PHONE");
  await expect(canvas.getByRole("button", { name: "인증 요청 발급" })).toBeEnabled();
} };
