INSERT INTO operations_audit_action_category(action, audit_category) VALUES
    ('PAYMENT_SETUP_RECOVERY_CASES_READ', 'FINANCIAL_TRANSACTION'),
    ('PAYMENT_SETUP_REPAIR_PROPOSALS_READ', 'FINANCIAL_TRANSACTION');
