package io.github.kdh949.beanflow.discovery.internal

import io.github.kdh949.beanflow.BEANFLOW_POSTGRES_IMAGE
import io.github.kdh949.beanflow.merchant.api.NearbyStoreProfileQuery
import io.github.kdh949.beanflow.merchant.internal.StoreDiscoveryProfileQueryRepository
import org.assertj.core.api.Assertions.assertThat
import org.flywaydb.core.Flyway
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.jdbc.datasource.DriverManagerDataSource
import org.springframework.jdbc.datasource.SingleConnectionDataSource
import org.testcontainers.containers.PostgreSQLContainer
import org.testcontainers.junit.jupiter.Container
import org.testcontainers.junit.jupiter.Testcontainers
import java.math.BigDecimal
import java.util.concurrent.TimeUnit
import kotlin.math.ceil

/**
 * Reproducible nearby-search measurement at two data scales.
 *
 * Opt-in only: set `BEANFLOW_BENCHMARK=true` (see `scripts/perf/nearby-store-search.sh`). It is
 * excluded from the normal suite because it seeds 110,000 rows and runs hundreds of queries.
 *
 * The dataset is generated by a closed formula rather than `random()`, so the same rows are
 * produced on every machine and every run. The query point, radius, page limit, warm-up count and
 * measured iteration count are all fixed below.
 */
@Testcontainers(disabledWithoutDocker = true)
@EnabledIfEnvironmentVariable(named = "BEANFLOW_BENCHMARK", matches = "true")
internal class NearbyStoreDiscoveryBenchmark {
    companion object {
        @Container
        val postgres: PostgreSQLContainer<*> = PostgreSQLContainer(BEANFLOW_POSTGRES_IMAGE)

        const val SMALL_SCALE = 10_000
        const val LARGE_SCALE = 100_000
        const val RADIUS_METERS = 1_000
        const val PAGE_LIMIT = 100
        const val WARM_UP_ITERATIONS = 20
        const val MEASURED_ITERATIONS = 200
        val QUERY_LATITUDE: BigDecimal = BigDecimal("37.5")
        val QUERY_LONGITUDE: BigDecimal = BigDecimal("127.0")
    }

    @Test
    fun `nearby search plan and latency at two data scales`() {
        val dataSource = DriverManagerDataSource(postgres.jdbcUrl, postgres.username, postgres.password)
        Flyway
            .configure()
            .dataSource(dataSource)
            .locations("classpath:db/migration")
            .load()
            .migrate()
        val jdbcTemplate = JdbcTemplate(dataSource)
        // A single reused connection keeps TCP connect and authentication out of the samples, so
        // the numbers describe query round-trip time rather than connection setup.
        val measuredConnection =
            SingleConnectionDataSource(postgres.jdbcUrl, postgres.username, postgres.password, true)
        val repository = StoreDiscoveryProfileQueryRepository(JdbcTemplate(measuredConnection))

        println("NEARBY_BENCHMARK_ENVIRONMENT ${environment(jdbcTemplate)}")
        println(
            "NEARBY_BENCHMARK_FIXED_CONDITIONS latitude=${QUERY_LATITUDE.toPlainString()} " +
                "longitude=${QUERY_LONGITUDE.toPlainString()} radiusMeters=$RADIUS_METERS limit=$PAGE_LIMIT " +
                "warmUp=$WARM_UP_ITERATIONS measured=$MEASURED_ITERATIONS",
        )

        var seeded = 0
        listOf(SMALL_SCALE, LARGE_SCALE).forEach { scale ->
            seedUpTo(jdbcTemplate, from = seeded, to = scale)
            seeded = scale
            jdbcTemplate.execute("VACUUM ANALYZE merchant_store_discovery_profile")
            jdbcTemplate.execute("VACUUM ANALYZE merchant_store")

            val matched = repository.findPickupCapableStoresNear(query()).size
            val plan = explain(jdbcTemplate)
            val samples = measure(repository)

            println("NEARBY_BENCHMARK_SCALE profiles=$scale matchedFirstPage=$matched")
            println("NEARBY_BENCHMARK_PLAN scale=$scale\n$plan")
            println(
                "NEARBY_BENCHMARK_LATENCY_MS scale=$scale " +
                    "p50=${"%.3f".format(percentile(samples, 50))} " +
                    "p95=${"%.3f".format(percentile(samples, 95))} " +
                    "p99=${"%.3f".format(percentile(samples, 99))} " +
                    "min=${"%.3f".format(samples.first())} max=${"%.3f".format(samples.last())} " +
                    "samples=${samples.size}",
            )

            // The measurement is only meaningful if the production predicate still reaches the GiST
            // index. The access method itself is the planner's choice and is recorded, not forced:
            // a bitmap path and a plain index scan are both acceptable.
            assertThat(plan)
                .describedAs("scale=%s plan must use the GiST index", scale)
                .containsPattern("(Index Scan|Bitmap Index Scan) (using|on) idx_store_discovery_profile_location")
        }
        assertThat(count(jdbcTemplate, "SELECT count(*) FROM merchant_store_discovery_profile")).isEqualTo(LARGE_SCALE.toLong())
        measuredConnection.destroy()
    }

    /**
     * Deterministic pseudo-uniform spread over a bounding box around the query point. Two coprime
     * multipliers give a repeatable low-discrepancy pattern without `random()`, so the dataset is
     * identical on every run.
     */
    private fun seedUpTo(
        jdbcTemplate: JdbcTemplate,
        from: Int,
        to: Int,
    ) {
        jdbcTemplate.update(
            """
            INSERT INTO merchant_store (id, accepting_orders, pickup_enabled, version)
            SELECT md5('nearby-benchmark:' || sequence)::uuid, true, true, 0
              FROM generate_series(?, ?) AS sequence
            """.trimIndent(),
            from,
            to - 1,
        )
        jdbcTemplate.update(
            """
            INSERT INTO merchant_store_discovery_profile (store_id, name, location)
            SELECT md5('nearby-benchmark:' || sequence)::uuid,
                   'Benchmark store ' || sequence,
                   ST_SetSRID(
                       ST_MakePoint(
                           126.80 + ((sequence * 7919) % 100000)::double precision / 100000.0 * 0.40,
                           37.35 + ((sequence * 6421) % 100000)::double precision / 100000.0 * 0.30
                       ),
                       4326
                   )::geography
              FROM generate_series(?, ?) AS sequence
            """.trimIndent(),
            from,
            to - 1,
        )
    }

    private fun query() =
        NearbyStoreProfileQuery(
            latitude = QUERY_LATITUDE,
            longitude = QUERY_LONGITUDE,
            radiusMeters = RADIUS_METERS,
            after = null,
            limit = PAGE_LIMIT + 1,
        )

    private fun measure(repository: StoreDiscoveryProfileQueryRepository): List<Double> {
        repeat(WARM_UP_ITERATIONS) { repository.findPickupCapableStoresNear(query()) }
        return (0 until MEASURED_ITERATIONS)
            .map {
                val startedAt = System.nanoTime()
                repository.findPickupCapableStoresNear(query())
                (System.nanoTime() - startedAt).toDouble() / TimeUnit.MILLISECONDS.toNanos(1)
            }.sorted()
    }

    /** Nearest-rank percentile over the sorted sample list. */
    private fun percentile(
        sorted: List<Double>,
        percentile: Int,
    ): Double {
        val rank = ceil(sorted.size * percentile / 100.0).toInt().coerceIn(1, sorted.size)
        return sorted[rank - 1]
    }

    private fun explain(jdbcTemplate: JdbcTemplate): String =
        jdbcTemplate
            .queryForList(
                """
                EXPLAIN (ANALYZE, BUFFERS)
                SELECT candidate.store_id, candidate.name, candidate.distance_micrometers
                  FROM (
                        SELECT profile.store_id AS store_id,
                               profile.name AS name,
                               floor(ST_Distance(profile.location, $QUERY_POINT) * 1000000)::bigint
                                   AS distance_micrometers
                          FROM merchant_store_discovery_profile profile
                          JOIN merchant_store store ON store.id = profile.store_id
                         WHERE ST_DWithin(profile.location, $QUERY_POINT, $RADIUS_METERS)
                           AND store.accepting_orders
                           AND store.pickup_enabled
                       ) AS candidate
                 ORDER BY candidate.distance_micrometers, candidate.store_id
                 LIMIT ${PAGE_LIMIT + 1}
                """.trimIndent(),
                String::class.java,
            ).joinToString("\n")

    private fun environment(jdbcTemplate: JdbcTemplate): String {
        val version = jdbcTemplate.queryForObject("SELECT version()", String::class.java)
        val postgis = jdbcTemplate.queryForObject("SELECT postgis_version()", String::class.java)
        return "postgres=\"$version\" postgis=\"$postgis\" jvm=\"${System.getProperty("java.version")}\" " +
            "os=\"${System.getProperty("os.name")} ${System.getProperty("os.arch")}\""
    }

    private fun count(
        jdbcTemplate: JdbcTemplate,
        sql: String,
    ): Long = jdbcTemplate.queryForObject(sql, Long::class.java)!!
}

private const val QUERY_POINT = "ST_SetSRID(ST_MakePoint(127.0, 37.5), 4326)::geography"
