#!/usr/bin/env bash
#
# Reproducible nearby-store-search measurement.
#
# Seeds two deterministic PostGIS datasets (10,000 and 100,000 Store/Profile rows plus seven
# operating-hours rows per Store), then records the query plan and latency distribution of the
# production first-page query at each scale. The dataset is generated by a closed formula, so
# re-running this script on the same machine reproduces the same rows.
#
# Fixed conditions (see NearbyStoreDiscoveryBenchmark for the authoritative values):
#   query point 127.0, 37.5   radius 1000 m   page limit 100 (+1 next-page probe)
#   20 warm-up iterations, 200 measured iterations per scale
#
# Requirements: Docker with the PostgreSQL 17 / PostGIS 3.5 image reachable. The image publishes a
# linux/amd64 manifest only, so an arm64 host runs it under emulation and the absolute numbers are
# not comparable with a native amd64 run.
#
# Usage:
#   scripts/perf/nearby-store-search.sh [output-file]
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

OUTPUT="${1:-build/reports/nearby-store-search-measurement.txt}"
mkdir -p "$(dirname "$OUTPUT")"

echo "Running the nearby store search measurement. This seeds 110,000 Store profiles plus weekly hours and may take several minutes."

BEANFLOW_BENCHMARK=true ./gradlew test \
  --tests '*NearbyStoreDiscoveryBenchmark' \
  --rerun-tasks \
  --info \
  2>&1 | grep -E 'NEARBY_BENCHMARK_|^ *(Limit|Sort|Nested Loop|Hash Join|Merge Join|Hash|CTE Scan|Index Scan|Seq Scan|Bitmap|Buffers|Planning|Execution|Sort Key|Sort Method|Index Cond|Filter|Rows Removed|->)' \
  | tee "$OUTPUT"

echo
echo "Measurement written to $OUTPUT"
echo "Record the actual values in docs/quality/nearby-store-discovery-performance-evidence.md."
echo "Do not claim an improvement without a comparable baseline captured under the same conditions."
